//
//  RNOpenGLBinder.cpp
//  Rayne
//
//  Copyright 2013 by Überpixel. All rights reserved.
//  Unauthorized use is punishable by torture, mutilation, and vivisection.
//

#include "RNOpenGL.h"
#include "RNBase.h"

// 1.0
PFNGLCULLFACEPROC glCullFace = nullptr;
PFNGLFRONTFACEPROC glFrontFace = nullptr;
PFNGLHINTPROC glHint = nullptr;
PFNGLLINEWIDTHPROC glLineWidth = nullptr;
PFNGLPOINTSIZEPROC glPointSize = nullptr;
PFNGLPOLYGONMODEPROC glPolygonMode = nullptr;
PFNGLSCISSORPROC glScissor = nullptr;
PFNGLTEXPARAMETERFPROC glTexParameterf = nullptr;
PFNGLTEXPARAMETERFVPROC glTexParameterfv = nullptr;
PFNGLTEXPARAMETERIPROC glTexParameteri = nullptr;
PFNGLTEXPARAMETERIVPROC glTexParameteriv = nullptr;
PFNGLTEXIMAGE1DPROC glTexImage1D = nullptr;
PFNGLTEXIMAGE2DPROC glTexImage2D = nullptr;
PFNGLDRAWBUFFERPROC glDrawBuffer = nullptr;
PFNGLCLEARPROC glClear = nullptr;
PFNGLCLEARCOLORPROC glClearColor = nullptr;
PFNGLCLEARSTENCILPROC glClearStencil = nullptr;
PFNGLCLEARDEPTHPROC glClearDepth = nullptr;
PFNGLSTENCILMASKPROC glStencilMask = nullptr;
PFNGLCOLORMASKPROC glColorMask = nullptr;
PFNGLDEPTHMASKPROC glDepthMask = nullptr;
PFNGLDISABLEPROC glDisable = nullptr;
PFNGLENABLEPROC glEnable = nullptr;
PFNGLFINISHPROC glFinish = nullptr;
PFNGLFLUSHPROC glFlush = nullptr;
PFNGLBLENDFUNCPROC glBlendFunc = nullptr;
PFNGLLOGICOPPROC glLogicOp = nullptr;
PFNGLSTENCILFUNCPROC glStencilFunc = nullptr;
PFNGLSTENCILOPPROC glStencilOp = nullptr;
PFNGLDEPTHFUNCPROC glDepthFunc = nullptr;
PFNGLPIXELSTOREFPROC glPixelStoref = nullptr;
PFNGLPIXELSTOREIPROC glPixelStorei = nullptr;
PFNGLREADBUFFERPROC glReadBuffer = nullptr;
PFNGLREADPIXELSPROC glReadPixels = nullptr;
PFNGLGETBOOLEANVPROC glGetBooleanv = nullptr;
PFNGLGETDOUBLEVPROC glGetDoublev = nullptr;
PFNGLGETERRORPROC glGetError = nullptr;
PFNGLGETFLOATVPROC glGetFloatv = nullptr;
PFNGLGETINTEGERVPROC glGetIntegerv = nullptr;
PFNGLGETSTRINGPROC glGetString = nullptr;
PFNGLGETTEXIMAGEPROC glGetTexImage = nullptr;
PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv = nullptr;
PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv = nullptr;
PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv = nullptr;
PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv = nullptr;
PFNGLISENABLEDPROC glIsEnabled = nullptr;
PFNGLDEPTHRANGEPROC glDepthRange = nullptr;
PFNGLVIEWPORTPROC glViewport = nullptr;

// 1.1
PFNGLDRAWARRAYSPROC glDrawArrays = nullptr;
PFNGLDRAWELEMENTSPROC glDrawElements = nullptr;
PFNGLGETPOINTERVPROC glGetPointerv = nullptr;
PFNGLPOLYGONOFFSETPROC glPolygonOffset = nullptr;
PFNGLCOPYTEXIMAGE1DPROC glCopyTexImage1D = nullptr;
PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D = nullptr;
PFNGLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D = nullptr;
PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D = nullptr;
PFNGLTEXSUBIMAGE1DPROC glTexSubImage1D = nullptr;
PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D = nullptr;
PFNGLBINDTEXTUREPROC glBindTexture = nullptr;
PFNGLDELETETEXTURESPROC glDeleteTextures = nullptr;
PFNGLGENTEXTURESPROC glGenTextures = nullptr;
PFNGLISTEXTUREPROC glIsTexture = nullptr;

// 1.2
PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements = nullptr;
PFNGLTEXIMAGE3DPROC glTexImage3D = nullptr;
PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D = nullptr;
PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D = nullptr;

// 1.3
PFNGLACTIVETEXTUREPROC glActiveTexture = nullptr;
PFNGLSAMPLECOVERAGEPROC glSampleCoverage = nullptr;
PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D = nullptr;
PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D = nullptr;
PFNGLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D = nullptr;
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D = nullptr;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D = nullptr;
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D = nullptr;
PFNGLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage = nullptr;

// 1.4
PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate = nullptr;
PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays = nullptr;
PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements = nullptr;
PFNGLPOINTPARAMETERFPROC glPointParameterf = nullptr;
PFNGLPOINTPARAMETERFVPROC glPointParameterfv = nullptr;
PFNGLPOINTPARAMETERIPROC glPointParameteri = nullptr;
PFNGLPOINTPARAMETERIVPROC glPointParameteriv = nullptr;
PFNGLBLENDCOLORPROC glBlendColor = nullptr;
PFNGLBLENDEQUATIONPROC glBlendEquation = nullptr;

// 1.5
PFNGLGENQUERIESPROC glGenQueries = nullptr;
PFNGLDELETEQUERIESPROC glDeleteQueries = nullptr;
PFNGLISQUERYPROC glIsQuery = nullptr;
PFNGLBEGINQUERYPROC glBeginQuery = nullptr;
PFNGLENDQUERYPROC glEndQuery = nullptr;
PFNGLGETQUERYIVPROC glGetQueryiv = nullptr;
PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv = nullptr;
PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv = nullptr;
PFNGLBINDBUFFERPROC glBindBuffer = nullptr;
PFNGLDELETEBUFFERSPROC glDeleteBuffers = nullptr;
PFNGLGENBUFFERSPROC glGenBuffers = nullptr;
PFNGLISBUFFERPROC glIsBuffer = nullptr;
PFNGLBUFFERDATAPROC glBufferData = nullptr;
PFNGLBUFFERSUBDATAPROC glBufferSubData = nullptr;
PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData = nullptr;
PFNGLMAPBUFFERPROC glMapBuffer = nullptr;
PFNGLUNMAPBUFFERPROC glUnmapBuffer = nullptr;
PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv = nullptr;
PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv = nullptr;

// 2.0
PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate = nullptr;
PFNGLDRAWBUFFERSPROC glDrawBuffers = nullptr;
PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate = nullptr;
PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate = nullptr;
PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate = nullptr;
PFNGLATTACHSHADERPROC glAttachShader = nullptr;
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation = nullptr;
PFNGLCOMPILESHADERPROC glCompileShader = nullptr;
PFNGLCREATEPROGRAMPROC glCreateProgram = nullptr;
PFNGLCREATESHADERPROC glCreateShader = nullptr;
PFNGLDELETEPROGRAMPROC glDeleteProgram = nullptr;
PFNGLDELETESHADERPROC glDeleteShader = nullptr;
PFNGLDETACHSHADERPROC glDetachShader = nullptr;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = nullptr;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = nullptr;
PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib = nullptr;
PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform = nullptr;
PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders = nullptr;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation = nullptr;
PFNGLGETPROGRAMIVPROC glGetProgramiv = nullptr;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = nullptr;
PFNGLGETSHADERIVPROC glGetShaderiv = nullptr;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = nullptr;
PFNGLGETSHADERSOURCEPROC glGetShaderSource = nullptr;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = nullptr;
PFNGLGETUNIFORMFVPROC glGetUniformfv = nullptr;
PFNGLGETUNIFORMIVPROC glGetUniformiv = nullptr;
PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv = nullptr;
PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv = nullptr;
PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv = nullptr;
PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv = nullptr;
PFNGLISPROGRAMPROC glIsProgram = nullptr;
PFNGLISSHADERPROC glIsShader = nullptr;
PFNGLLINKPROGRAMPROC glLinkProgram = nullptr;
PFNGLSHADERSOURCEPROC glShaderSource = nullptr;
PFNGLUSEPROGRAMPROC glUseProgram = nullptr;
PFNGLUNIFORM1FPROC glUniform1f = nullptr;
PFNGLUNIFORM2FPROC glUniform2f = nullptr;
PFNGLUNIFORM3FPROC glUniform3f = nullptr;
PFNGLUNIFORM4FPROC glUniform4f = nullptr;
PFNGLUNIFORM1IPROC glUniform1i = nullptr;
PFNGLUNIFORM2IPROC glUniform2i = nullptr;
PFNGLUNIFORM3IPROC glUniform3i = nullptr;
PFNGLUNIFORM4IPROC glUniform4i = nullptr;
PFNGLUNIFORM1FVPROC glUniform1fv = nullptr;
PFNGLUNIFORM2FVPROC glUniform2fv = nullptr;
PFNGLUNIFORM3FVPROC glUniform3fv = nullptr;
PFNGLUNIFORM4FVPROC glUniform4fv = nullptr;
PFNGLUNIFORM1IVPROC glUniform1iv = nullptr;
PFNGLUNIFORM2IVPROC glUniform2iv = nullptr;
PFNGLUNIFORM3IVPROC glUniform3iv = nullptr;
PFNGLUNIFORM4IVPROC glUniform4iv = nullptr;
PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv = nullptr;
PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv = nullptr;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv = nullptr;
PFNGLVALIDATEPROGRAMPROC glValidateProgram = nullptr;
PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d = nullptr;
PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv = nullptr;
PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f = nullptr;
PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv = nullptr;
PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s = nullptr;
PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv = nullptr;
PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d = nullptr;
PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv = nullptr;
PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f = nullptr;
PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv = nullptr;
PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s = nullptr;
PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv = nullptr;
PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d = nullptr;
PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv = nullptr;
PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f = nullptr;
PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv = nullptr;
PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s = nullptr;
PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv = nullptr;
PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv = nullptr;
PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv = nullptr;
PFNGLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv = nullptr;
PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub = nullptr;
PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv = nullptr;
PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv = nullptr;
PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv = nullptr;
PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv = nullptr;
PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d = nullptr;
PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv = nullptr;
PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f = nullptr;
PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv = nullptr;
PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv = nullptr;
PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s = nullptr;
PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv = nullptr;
PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv = nullptr;
PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv = nullptr;
PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv = nullptr;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = nullptr;

// 2.1
PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv = nullptr;
PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv = nullptr;
PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv = nullptr;
PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv = nullptr;
PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv = nullptr;
PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv = nullptr;

// 3.0
PFNGLCOLORMASKIPROC glColorMaski = nullptr;
PFNGLGETBOOLEANI_VPROC glGetBooleani_v = nullptr;
PFNGLGETINTEGERI_VPROC glGetIntegeri_v = nullptr;
PFNGLENABLEIPROC glEnablei = nullptr;
PFNGLDISABLEIPROC glDisablei = nullptr;
PFNGLISENABLEDIPROC glIsEnabledi = nullptr;
PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback = nullptr;
PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback = nullptr;
PFNGLBINDBUFFERRANGEPROC glBindBufferRange = nullptr;
PFNGLBINDBUFFERBASEPROC glBindBufferBase = nullptr;
PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings = nullptr;
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying = nullptr;
PFNGLCLAMPCOLORPROC glClampColor = nullptr;
PFNGLBEGINCONDITIONALRENDERPROC glBeginConditionalRender = nullptr;
PFNGLENDCONDITIONALRENDERPROC glEndConditionalRender = nullptr;
PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer = nullptr;
PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv = nullptr;
PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv = nullptr;
PFNGLVERTEXATTRIBI1IPROC glVertexAttribI1i = nullptr;
PFNGLVERTEXATTRIBI2IPROC glVertexAttribI2i = nullptr;
PFNGLVERTEXATTRIBI3IPROC glVertexAttribI3i = nullptr;
PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i = nullptr;
PFNGLVERTEXATTRIBI1UIPROC glVertexAttribI1ui = nullptr;
PFNGLVERTEXATTRIBI2UIPROC glVertexAttribI2ui = nullptr;
PFNGLVERTEXATTRIBI3UIPROC glVertexAttribI3ui = nullptr;
PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui = nullptr;
PFNGLVERTEXATTRIBI1IVPROC glVertexAttribI1iv = nullptr;
PFNGLVERTEXATTRIBI2IVPROC glVertexAttribI2iv = nullptr;
PFNGLVERTEXATTRIBI3IVPROC glVertexAttribI3iv = nullptr;
PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv = nullptr;
PFNGLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv = nullptr;
PFNGLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv = nullptr;
PFNGLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv = nullptr;
PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv = nullptr;
PFNGLVERTEXATTRIBI4BVPROC glVertexAttribI4bv = nullptr;
PFNGLVERTEXATTRIBI4SVPROC glVertexAttribI4sv = nullptr;
PFNGLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv = nullptr;
PFNGLVERTEXATTRIBI4USVPROC glVertexAttribI4usv = nullptr;
PFNGLGETUNIFORMUIVPROC glGetUniformuiv = nullptr;
PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation = nullptr;
PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation = nullptr;
PFNGLUNIFORM1UIPROC glUniform1ui = nullptr;
PFNGLUNIFORM2UIPROC glUniform2ui = nullptr;
PFNGLUNIFORM3UIPROC glUniform3ui = nullptr;
PFNGLUNIFORM4UIPROC glUniform4ui = nullptr;
PFNGLUNIFORM1UIVPROC glUniform1uiv = nullptr;
PFNGLUNIFORM2UIVPROC glUniform2uiv = nullptr;
PFNGLUNIFORM3UIVPROC glUniform3uiv = nullptr;
PFNGLUNIFORM4UIVPROC glUniform4uiv = nullptr;
PFNGLTEXPARAMETERIIVPROC glTexParameterIiv = nullptr;
PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv = nullptr;
PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv = nullptr;
PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv = nullptr;
PFNGLCLEARBUFFERIVPROC glClearBufferiv = nullptr;
PFNGLCLEARBUFFERUIVPROC glClearBufferuiv = nullptr;
PFNGLCLEARBUFFERFVPROC glClearBufferfv = nullptr;
PFNGLCLEARBUFFERFIPROC glClearBufferfi = nullptr;
PFNGLGETSTRINGIPROC glGetStringi = nullptr;
PFNGLISRENDERBUFFERPROC glIsRenderbuffer = nullptr;
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer = nullptr;
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers = nullptr;
PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers = nullptr;
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage = nullptr;
PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv = nullptr;
PFNGLISFRAMEBUFFERPROC glIsFramebuffer = nullptr;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer = nullptr;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers = nullptr;
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers = nullptr;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus = nullptr;
PFNGLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D = nullptr;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D = nullptr;
PFNGLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D = nullptr;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer = nullptr;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv = nullptr;
PFNGLGENERATEMIPMAPPROC glGenerateMipmap = nullptr;
PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer = nullptr;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample = nullptr;
PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer = nullptr;
PFNGLMAPBUFFERRANGEPROC glMapBufferRange = nullptr;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange = nullptr;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray = nullptr;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays = nullptr;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = nullptr;
PFNGLISVERTEXARRAYPROC glIsVertexArray = nullptr;

// 3.1
PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced = nullptr;
PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced = nullptr;
PFNGLTEXBUFFERPROC glTexBuffer = nullptr;
PFNGLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex = nullptr;
PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData = nullptr;
PFNGLGETUNIFORMINDICESPROC glGetUniformIndices = nullptr;
PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv = nullptr;
PFNGLGETACTIVEUNIFORMNAMEPROC glGetActiveUniformName = nullptr;
PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex = nullptr;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv = nullptr;
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName = nullptr;
PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding = nullptr;

// 3.2
PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex = nullptr;
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex = nullptr;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex = nullptr;
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex = nullptr;
PFNGLPROVOKINGVERTEXPROC glProvokingVertex = nullptr;
PFNGLFENCESYNCPROC glFenceSync = nullptr;
PFNGLISSYNCPROC glIsSync = nullptr;
PFNGLDELETESYNCPROC glDeleteSync = nullptr;
PFNGLCLIENTWAITSYNCPROC glClientWaitSync = nullptr;
PFNGLWAITSYNCPROC glWaitSync = nullptr;
PFNGLGETINTEGER64VPROC glGetInteger64v = nullptr;
PFNGLGETSYNCIVPROC glGetSynciv = nullptr;
PFNGLGETINTEGER64I_VPROC glGetInteger64i_v = nullptr;
PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v = nullptr;
PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture = nullptr;
PFNGLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample = nullptr;
PFNGLTEXIMAGE3DMULTISAMPLEPROC glTexImage3DMultisample = nullptr;
PFNGLGETMULTISAMPLEFVPROC glGetMultisamplefv = nullptr;
PFNGLSAMPLEMASKIPROC glSampleMaski = nullptr;

// 3.3
PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed = nullptr;
PFNGLGETFRAGDATAINDEXPROC glGetFragDataIndex = nullptr;
PFNGLGENSAMPLERSPROC glGenSamplers = nullptr;
PFNGLDELETESAMPLERSPROC glDeleteSamplers = nullptr;
PFNGLISSAMPLERPROC glIsSampler = nullptr;
PFNGLBINDSAMPLERPROC glBindSampler = nullptr;
PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri = nullptr;
PFNGLSAMPLERPARAMETERIVPROC glSamplerParameteriv = nullptr;
PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf = nullptr;
PFNGLSAMPLERPARAMETERFVPROC glSamplerParameterfv = nullptr;
PFNGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv = nullptr;
PFNGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv = nullptr;
PFNGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv = nullptr;
PFNGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv = nullptr;
PFNGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv = nullptr;
PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv = nullptr;
PFNGLQUERYCOUNTERPROC glQueryCounter = nullptr;
PFNGLGETQUERYOBJECTI64VPROC glGetQueryObjecti64v = nullptr;
PFNGLGETQUERYOBJECTUI64VPROC glGetQueryObjectui64v = nullptr;
PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor = nullptr;
PFNGLVERTEXATTRIBP1UIPROC glVertexAttribP1ui = nullptr;
PFNGLVERTEXATTRIBP1UIVPROC glVertexAttribP1uiv = nullptr;
PFNGLVERTEXATTRIBP2UIPROC glVertexAttribP2ui = nullptr;
PFNGLVERTEXATTRIBP2UIVPROC glVertexAttribP2uiv = nullptr;
PFNGLVERTEXATTRIBP3UIPROC glVertexAttribP3ui = nullptr;
PFNGLVERTEXATTRIBP3UIVPROC glVertexAttribP3uiv = nullptr;
PFNGLVERTEXATTRIBP4UIPROC glVertexAttribP4ui = nullptr;
PFNGLVERTEXATTRIBP4UIVPROC glVertexAttribP4uiv = nullptr;

// 4.0
PFNGLMINSAMPLESHADINGPROC glMinSampleShading = nullptr;
PFNGLBLENDEQUATIONIPROC glBlendEquationi = nullptr;
PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei = nullptr;
PFNGLBLENDFUNCIPROC glBlendFunci = nullptr;
PFNGLBLENDFUNCSEPARATEIPROC glBlendFuncSeparatei = nullptr;
PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect = nullptr;
PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect = nullptr;
PFNGLUNIFORM1DPROC glUniform1d = nullptr;
PFNGLUNIFORM2DPROC glUniform2d = nullptr;
PFNGLUNIFORM3DPROC glUniform3d = nullptr;
PFNGLUNIFORM4DPROC glUniform4d = nullptr;
PFNGLUNIFORM1DVPROC glUniform1dv = nullptr;
PFNGLUNIFORM2DVPROC glUniform2dv = nullptr;
PFNGLUNIFORM3DVPROC glUniform3dv = nullptr;
PFNGLUNIFORM4DVPROC glUniform4dv = nullptr;
PFNGLUNIFORMMATRIX2DVPROC glUniformMatrix2dv = nullptr;
PFNGLUNIFORMMATRIX3DVPROC glUniformMatrix3dv = nullptr;
PFNGLUNIFORMMATRIX4DVPROC glUniformMatrix4dv = nullptr;
PFNGLUNIFORMMATRIX2X3DVPROC glUniformMatrix2x3dv = nullptr;
PFNGLUNIFORMMATRIX2X4DVPROC glUniformMatrix2x4dv = nullptr;
PFNGLUNIFORMMATRIX3X2DVPROC glUniformMatrix3x2dv = nullptr;
PFNGLUNIFORMMATRIX3X4DVPROC glUniformMatrix3x4dv = nullptr;
PFNGLUNIFORMMATRIX4X2DVPROC glUniformMatrix4x2dv = nullptr;
PFNGLUNIFORMMATRIX4X3DVPROC glUniformMatrix4x3dv = nullptr;
PFNGLGETUNIFORMDVPROC glGetUniformdv = nullptr;
PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC glGetSubroutineUniformLocation = nullptr;
PFNGLGETSUBROUTINEINDEXPROC glGetSubroutineIndex = nullptr;
PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC glGetActiveSubroutineUniformiv = nullptr;
PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC glGetActiveSubroutineUniformName = nullptr;
PFNGLGETACTIVESUBROUTINENAMEPROC glGetActiveSubroutineName = nullptr;
PFNGLUNIFORMSUBROUTINESUIVPROC glUniformSubroutinesuiv = nullptr;
PFNGLGETUNIFORMSUBROUTINEUIVPROC glGetUniformSubroutineuiv = nullptr;
PFNGLGETPROGRAMSTAGEIVPROC glGetProgramStageiv = nullptr;
PFNGLPATCHPARAMETERIPROC glPatchParameteri = nullptr;
PFNGLPATCHPARAMETERFVPROC glPatchParameterfv = nullptr;
PFNGLBINDTRANSFORMFEEDBACKPROC glBindTransformFeedback = nullptr;
PFNGLDELETETRANSFORMFEEDBACKSPROC glDeleteTransformFeedbacks = nullptr;
PFNGLGENTRANSFORMFEEDBACKSPROC glGenTransformFeedbacks = nullptr;
PFNGLISTRANSFORMFEEDBACKPROC glIsTransformFeedback = nullptr;
PFNGLPAUSETRANSFORMFEEDBACKPROC glPauseTransformFeedback = nullptr;
PFNGLRESUMETRANSFORMFEEDBACKPROC glResumeTransformFeedback = nullptr;
PFNGLDRAWTRANSFORMFEEDBACKPROC glDrawTransformFeedback = nullptr;
PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC glDrawTransformFeedbackStream = nullptr;
PFNGLBEGINQUERYINDEXEDPROC glBeginQueryIndexed = nullptr;
PFNGLENDQUERYINDEXEDPROC glEndQueryIndexed = nullptr;
PFNGLGETQUERYINDEXEDIVPROC glGetQueryIndexediv = nullptr;

// 4.1
PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler = nullptr;
PFNGLSHADERBINARYPROC glShaderBinary = nullptr;
PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat = nullptr;
PFNGLDEPTHRANGEFPROC glDepthRangef = nullptr;
PFNGLCLEARDEPTHFPROC glClearDepthf = nullptr;
PFNGLGETPROGRAMBINARYPROC glGetProgramBinary = nullptr;
PFNGLPROGRAMBINARYPROC glProgramBinary = nullptr;
PFNGLPROGRAMPARAMETERIPROC glProgramParameteri = nullptr;
PFNGLUSEPROGRAMSTAGESPROC glUseProgramStages = nullptr;
PFNGLACTIVESHADERPROGRAMPROC glActiveShaderProgram = nullptr;
PFNGLCREATESHADERPROGRAMVPROC glCreateShaderProgramv = nullptr;
PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline = nullptr;
PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines = nullptr;
PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines = nullptr;
PFNGLISPROGRAMPIPELINEPROC glIsProgramPipeline = nullptr;
PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramPipelineiv = nullptr;
PFNGLPROGRAMUNIFORM1IPROC glProgramUniform1i = nullptr;
PFNGLPROGRAMUNIFORM1IVPROC glProgramUniform1iv = nullptr;
PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f = nullptr;
PFNGLPROGRAMUNIFORM1FVPROC glProgramUniform1fv = nullptr;
PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d = nullptr;
PFNGLPROGRAMUNIFORM1DVPROC glProgramUniform1dv = nullptr;
PFNGLPROGRAMUNIFORM1UIPROC glProgramUniform1ui = nullptr;
PFNGLPROGRAMUNIFORM1UIVPROC glProgramUniform1uiv = nullptr;
PFNGLPROGRAMUNIFORM2IPROC glProgramUniform2i = nullptr;
PFNGLPROGRAMUNIFORM2IVPROC glProgramUniform2iv = nullptr;
PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f = nullptr;
PFNGLPROGRAMUNIFORM2FVPROC glProgramUniform2fv = nullptr;
PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d = nullptr;
PFNGLPROGRAMUNIFORM2DVPROC glProgramUniform2dv = nullptr;
PFNGLPROGRAMUNIFORM2UIPROC glProgramUniform2ui = nullptr;
PFNGLPROGRAMUNIFORM2UIVPROC glProgramUniform2uiv = nullptr;
PFNGLPROGRAMUNIFORM3IPROC glProgramUniform3i = nullptr;
PFNGLPROGRAMUNIFORM3IVPROC glProgramUniform3iv = nullptr;
PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f = nullptr;
PFNGLPROGRAMUNIFORM3FVPROC glProgramUniform3fv = nullptr;
PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d = nullptr;
PFNGLPROGRAMUNIFORM3DVPROC glProgramUniform3dv = nullptr;
PFNGLPROGRAMUNIFORM3UIPROC glProgramUniform3ui = nullptr;
PFNGLPROGRAMUNIFORM3UIVPROC glProgramUniform3uiv = nullptr;
PFNGLPROGRAMUNIFORM4IPROC glProgramUniform4i = nullptr;
PFNGLPROGRAMUNIFORM4IVPROC glProgramUniform4iv = nullptr;
PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f = nullptr;
PFNGLPROGRAMUNIFORM4FVPROC glProgramUniform4fv = nullptr;
PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d = nullptr;
PFNGLPROGRAMUNIFORM4DVPROC glProgramUniform4dv = nullptr;
PFNGLPROGRAMUNIFORM4UIPROC glProgramUniform4ui = nullptr;
PFNGLPROGRAMUNIFORM4UIVPROC glProgramUniform4uiv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX2FVPROC glProgramUniformMatrix2fv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX2DVPROC glProgramUniformMatrix2dv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX3DVPROC glProgramUniformMatrix3dv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX4DVPROC glProgramUniformMatrix4dv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glProgramUniformMatrix2x3fv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glProgramUniformMatrix3x2fv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glProgramUniformMatrix2x4fv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glProgramUniformMatrix4x2fv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glProgramUniformMatrix3x4fv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glProgramUniformMatrix4x3fv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC glProgramUniformMatrix2x3dv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC glProgramUniformMatrix3x2dv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC glProgramUniformMatrix2x4dv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC glProgramUniformMatrix4x2dv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC glProgramUniformMatrix3x4dv = nullptr;
PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC glProgramUniformMatrix4x3dv = nullptr;
PFNGLVALIDATEPROGRAMPIPELINEPROC glValidateProgramPipeline = nullptr;
PFNGLGETPROGRAMPIPELINEINFOLOGPROC glGetProgramPipelineInfoLog = nullptr;
PFNGLVERTEXATTRIBL1DPROC glVertexAttribL1d = nullptr;
PFNGLVERTEXATTRIBL2DPROC glVertexAttribL2d = nullptr;
PFNGLVERTEXATTRIBL3DPROC glVertexAttribL3d = nullptr;
PFNGLVERTEXATTRIBL4DPROC glVertexAttribL4d = nullptr;
PFNGLVERTEXATTRIBL1DVPROC glVertexAttribL1dv = nullptr;
PFNGLVERTEXATTRIBL2DVPROC glVertexAttribL2dv = nullptr;
PFNGLVERTEXATTRIBL3DVPROC glVertexAttribL3dv = nullptr;
PFNGLVERTEXATTRIBL4DVPROC glVertexAttribL4dv = nullptr;
PFNGLVERTEXATTRIBLPOINTERPROC glVertexAttribLPointer = nullptr;
PFNGLGETVERTEXATTRIBLDVPROC glGetVertexAttribLdv = nullptr;
PFNGLVIEWPORTARRAYVPROC glViewportArrayv = nullptr;
PFNGLVIEWPORTINDEXEDFPROC glViewportIndexedf = nullptr;
PFNGLVIEWPORTINDEXEDFVPROC glViewportIndexedfv = nullptr;
PFNGLSCISSORARRAYVPROC glScissorArrayv = nullptr;
PFNGLSCISSORINDEXEDPROC glScissorIndexed = nullptr;
PFNGLSCISSORINDEXEDVPROC glScissorIndexedv = nullptr;
PFNGLDEPTHRANGEARRAYVPROC glDepthRangeArrayv = nullptr;
PFNGLDEPTHRANGEINDEXEDPROC glDepthRangeIndexed = nullptr;
PFNGLGETFLOATI_VPROC glGetFloati_v = nullptr;
PFNGLGETDOUBLEI_VPROC glGetDoublei_v = nullptr;

// Binding
namespace RN
{
	template<class T>
	void BindOpenGLFunction(T& ptr, const char *name)
	{
		ptr = reinterpret_cast<T>(dlsym(RTLD_NEXT, name));
	}
	
#define BindOpenGL(name) BindOpenGLFunction(name, #name)
	
	void BindOpenGLCore()
	{
		// 1.0
		BindOpenGL(glCullFace);
		BindOpenGL(glFrontFace);
		BindOpenGL(glHint);
		BindOpenGL(glLineWidth);
		BindOpenGL(glPointSize);
		BindOpenGL(glPolygonMode);
		BindOpenGL(glScissor);
		BindOpenGL(glTexParameterf);
		BindOpenGL(glTexParameterfv);
		BindOpenGL(glTexParameteri);
		BindOpenGL(glTexParameteriv);
		BindOpenGL(glTexImage1D);
		BindOpenGL(glTexImage2D);
		BindOpenGL(glDrawBuffer);
		BindOpenGL(glClear);
		BindOpenGL(glClearColor);
		BindOpenGL(glClearStencil);
		BindOpenGL(glClearDepth);
		BindOpenGL(glStencilMask);
		BindOpenGL(glColorMask);
		BindOpenGL(glDepthMask);
		BindOpenGL(glDisable);
		BindOpenGL(glEnable);
		BindOpenGL(glFinish);
		BindOpenGL(glFlush);
		BindOpenGL(glBlendFunc);
		BindOpenGL(glLogicOp);
		BindOpenGL(glStencilFunc);
		BindOpenGL(glStencilOp);
		BindOpenGL(glDepthFunc);
		BindOpenGL(glPixelStoref);
		BindOpenGL(glPixelStorei);
		BindOpenGL(glReadBuffer);
		BindOpenGL(glReadPixels);
		BindOpenGL(glGetBooleanv);
		BindOpenGL(glGetDoublev);
		BindOpenGL(glGetError);
		BindOpenGL(glGetFloatv);
		BindOpenGL(glGetIntegerv);
		BindOpenGL(glGetString);
		BindOpenGL(glGetTexImage);
		BindOpenGL(glGetTexParameterfv);
		BindOpenGL(glGetTexParameteriv);
		BindOpenGL(glGetTexLevelParameterfv);
		BindOpenGL(glGetTexLevelParameteriv);
		BindOpenGL(glIsEnabled);
		BindOpenGL(glDepthRange);
		BindOpenGL(glViewport);
		
		// 1.1
		BindOpenGL(glDrawArrays);
		BindOpenGL(glDrawElements);
		BindOpenGL(glGetPointerv);
		BindOpenGL(glPolygonOffset);
		BindOpenGL(glCopyTexImage1D);
		BindOpenGL(glCopyTexImage2D);
		BindOpenGL(glCopyTexSubImage1D);
		BindOpenGL(glCopyTexSubImage2D);
		BindOpenGL(glTexSubImage1D);
		BindOpenGL(glTexSubImage2D);
		BindOpenGL(glBindTexture);
		BindOpenGL(glDeleteTextures);
		BindOpenGL(glGenTextures);
		BindOpenGL(glIsTexture);
		
		// 1.2
		BindOpenGL(glDrawRangeElements);
		BindOpenGL(glTexImage3D);
		BindOpenGL(glTexSubImage3D);
		BindOpenGL(glCopyTexSubImage3D);
		
		// 1.3
		BindOpenGL(glActiveTexture);
		BindOpenGL(glSampleCoverage);
		BindOpenGL(glCompressedTexImage3D);
		BindOpenGL(glCompressedTexImage2D);
		BindOpenGL(glCompressedTexImage1D);
		BindOpenGL(glCompressedTexSubImage3D);
		BindOpenGL(glCompressedTexSubImage2D);
		BindOpenGL(glCompressedTexSubImage1D);
		BindOpenGL(glGetCompressedTexImage);
		
		// 1.4
		BindOpenGL(glBlendFuncSeparate);
		BindOpenGL(glMultiDrawArrays);
		BindOpenGL(glMultiDrawElements);
		BindOpenGL(glPointParameterf);
		BindOpenGL(glPointParameterfv);
		BindOpenGL(glPointParameteri);
		BindOpenGL(glPointParameteriv);
		BindOpenGL(glBlendColor);
		BindOpenGL(glBlendEquation);
		
		// 1.5
		BindOpenGL(glGenQueries);
		BindOpenGL(glDeleteQueries);
		BindOpenGL(glIsQuery);
		BindOpenGL(glBeginQuery);
		BindOpenGL(glEndQuery);
		BindOpenGL(glGetQueryiv);
		BindOpenGL(glGetQueryObjectiv);
		BindOpenGL(glGetQueryObjectuiv);
		BindOpenGL(glBindBuffer);
		BindOpenGL(glDeleteBuffers);
		BindOpenGL(glGenBuffers);
		BindOpenGL(glIsBuffer);
		BindOpenGL(glBufferData);
		BindOpenGL(glBufferSubData);
		BindOpenGL(glGetBufferSubData);
		BindOpenGL(glMapBuffer);
		BindOpenGL(glUnmapBuffer);
		BindOpenGL(glGetBufferParameteriv);
		BindOpenGL(glGetBufferPointerv);
		
		// 2.0
		BindOpenGL(glBlendEquationSeparate);
		BindOpenGL(glDrawBuffers);
		BindOpenGL(glStencilOpSeparate);
		BindOpenGL(glStencilFuncSeparate);
		BindOpenGL(glStencilMaskSeparate);
		BindOpenGL(glAttachShader);
		BindOpenGL(glBindAttribLocation);
		BindOpenGL(glCompileShader);
		BindOpenGL(glCreateProgram);
		BindOpenGL(glCreateShader);
		BindOpenGL(glDeleteProgram);
		BindOpenGL(glDeleteShader);
		BindOpenGL(glDetachShader);
		BindOpenGL(glDisableVertexAttribArray);
		BindOpenGL(glEnableVertexAttribArray);
		BindOpenGL(glGetActiveAttrib);
		BindOpenGL(glGetActiveUniform);
		BindOpenGL(glGetAttachedShaders);
		BindOpenGL(glGetAttribLocation);
		BindOpenGL(glGetProgramiv);
		BindOpenGL(glGetProgramInfoLog);
		BindOpenGL(glGetShaderiv);
		BindOpenGL(glGetShaderInfoLog);
		BindOpenGL(glGetShaderSource);
		BindOpenGL(glGetUniformLocation);
		BindOpenGL(glGetUniformfv);
		BindOpenGL(glGetUniformiv);
		BindOpenGL(glGetVertexAttribdv);
		BindOpenGL(glGetVertexAttribfv);
		BindOpenGL(glGetVertexAttribiv);
		BindOpenGL(glGetVertexAttribPointerv);
		BindOpenGL(glIsProgram);
		BindOpenGL(glIsShader);
		BindOpenGL(glLinkProgram);
		BindOpenGL(glShaderSource);
		BindOpenGL(glUseProgram);
		BindOpenGL(glUniform1f);
		BindOpenGL(glUniform2f);
		BindOpenGL(glUniform3f);
		BindOpenGL(glUniform4f);
		BindOpenGL(glUniform1i);
		BindOpenGL(glUniform2i);
		BindOpenGL(glUniform3i);
		BindOpenGL(glUniform4i);
		BindOpenGL(glUniform1fv);
		BindOpenGL(glUniform2fv);
		BindOpenGL(glUniform3fv);
		BindOpenGL(glUniform4fv);
		BindOpenGL(glUniform1iv);
		BindOpenGL(glUniform2iv);
		BindOpenGL(glUniform3iv);
		BindOpenGL(glUniform4iv);
		BindOpenGL(glUniformMatrix2fv);
		BindOpenGL(glUniformMatrix3fv);
		BindOpenGL(glUniformMatrix4fv);
		BindOpenGL(glValidateProgram);
		BindOpenGL(glVertexAttrib1d);
		BindOpenGL(glVertexAttrib1dv);
		BindOpenGL(glVertexAttrib1f);
		BindOpenGL(glVertexAttrib1fv);
		BindOpenGL(glVertexAttrib1s);
		BindOpenGL(glVertexAttrib1sv);
		BindOpenGL(glVertexAttrib2d);
		BindOpenGL(glVertexAttrib2dv);
		BindOpenGL(glVertexAttrib2f);
		BindOpenGL(glVertexAttrib2fv);
		BindOpenGL(glVertexAttrib2s);
		BindOpenGL(glVertexAttrib2sv);
		BindOpenGL(glVertexAttrib3d);
		BindOpenGL(glVertexAttrib3dv);
		BindOpenGL(glVertexAttrib3f);
		BindOpenGL(glVertexAttrib3fv);
		BindOpenGL(glVertexAttrib3s);
		BindOpenGL(glVertexAttrib3sv);
		BindOpenGL(glVertexAttrib4Nbv);
		BindOpenGL(glVertexAttrib4Niv);
		BindOpenGL(glVertexAttrib4Nsv);
		BindOpenGL(glVertexAttrib4Nub);
		BindOpenGL(glVertexAttrib4Nubv);
		BindOpenGL(glVertexAttrib4Nuiv);
		BindOpenGL(glVertexAttrib4Nusv);
		BindOpenGL(glVertexAttrib4bv);
		BindOpenGL(glVertexAttrib4d);
		BindOpenGL(glVertexAttrib4dv);
		BindOpenGL(glVertexAttrib4f);
		BindOpenGL(glVertexAttrib4fv);
		BindOpenGL(glVertexAttrib4iv);
		BindOpenGL(glVertexAttrib4s);
		BindOpenGL(glVertexAttrib4sv);
		BindOpenGL(glVertexAttrib4ubv);
		BindOpenGL(glVertexAttrib4uiv);
		BindOpenGL(glVertexAttrib4usv);
		BindOpenGL(glVertexAttribPointer);
		
		// 2.1
		BindOpenGL(glUniformMatrix2x3fv);
		BindOpenGL(glUniformMatrix3x2fv);
		BindOpenGL(glUniformMatrix2x4fv);
		BindOpenGL(glUniformMatrix4x2fv);
		BindOpenGL(glUniformMatrix3x4fv);
		BindOpenGL(glUniformMatrix4x3fv);
	}
	
	void BindOpenGLFunctions(gl::Version version)
	{
		if(version >= gl::Version::Core3_2)
		{
			// 3.0
			BindOpenGL(glColorMaski);
			BindOpenGL(glGetBooleani_v);
			BindOpenGL(glGetIntegeri_v);
			BindOpenGL(glEnablei);
			BindOpenGL(glDisablei);
			BindOpenGL(glIsEnabledi);
			BindOpenGL(glBeginTransformFeedback);
			BindOpenGL(glEndTransformFeedback);
			BindOpenGL(glBindBufferRange);
			BindOpenGL(glBindBufferBase);
			BindOpenGL(glTransformFeedbackVaryings);
			BindOpenGL(glGetTransformFeedbackVarying);
			BindOpenGL(glClampColor);
			BindOpenGL(glBeginConditionalRender);
			BindOpenGL(glEndConditionalRender);
			BindOpenGL(glVertexAttribIPointer);
			BindOpenGL(glGetVertexAttribIiv);
			BindOpenGL(glGetVertexAttribIuiv);
			BindOpenGL(glVertexAttribI1i);
			BindOpenGL(glVertexAttribI2i);
			BindOpenGL(glVertexAttribI3i);
			BindOpenGL(glVertexAttribI4i);
			BindOpenGL(glVertexAttribI1ui);
			BindOpenGL(glVertexAttribI2ui);
			BindOpenGL(glVertexAttribI3ui);
			BindOpenGL(glVertexAttribI4ui);
			BindOpenGL(glVertexAttribI1iv);
			BindOpenGL(glVertexAttribI2iv);
			BindOpenGL(glVertexAttribI3iv);
			BindOpenGL(glVertexAttribI4iv);
			BindOpenGL(glVertexAttribI1uiv);
			BindOpenGL(glVertexAttribI2uiv);
			BindOpenGL(glVertexAttribI3uiv);
			BindOpenGL(glVertexAttribI4uiv);
			BindOpenGL(glVertexAttribI4bv);
			BindOpenGL(glVertexAttribI4sv);
			BindOpenGL(glVertexAttribI4ubv);
			BindOpenGL(glVertexAttribI4usv);
			BindOpenGL(glGetUniformuiv);
			BindOpenGL(glBindFragDataLocation);
			BindOpenGL(glGetFragDataLocation);
			BindOpenGL(glUniform1ui);
			BindOpenGL(glUniform2ui);
			BindOpenGL(glUniform3ui);
			BindOpenGL(glUniform4ui);
			BindOpenGL(glUniform1uiv);
			BindOpenGL(glUniform2uiv);
			BindOpenGL(glUniform3uiv);
			BindOpenGL(glUniform4uiv);
			BindOpenGL(glTexParameterIiv);
			BindOpenGL(glTexParameterIuiv);
			BindOpenGL(glGetTexParameterIiv);
			BindOpenGL(glGetTexParameterIuiv);
			BindOpenGL(glClearBufferiv);
			BindOpenGL(glClearBufferuiv);
			BindOpenGL(glClearBufferfv);
			BindOpenGL(glClearBufferfi);
			BindOpenGL(glGetStringi);
			BindOpenGL(glIsRenderbuffer);
			BindOpenGL(glBindRenderbuffer);
			BindOpenGL(glDeleteRenderbuffers);
			BindOpenGL(glGenRenderbuffers);
			BindOpenGL(glRenderbufferStorage);
			BindOpenGL(glGetRenderbufferParameteriv);
			BindOpenGL(glIsFramebuffer);
			BindOpenGL(glBindFramebuffer);
			BindOpenGL(glDeleteFramebuffers);
			BindOpenGL(glGenFramebuffers);
			BindOpenGL(glCheckFramebufferStatus);
			BindOpenGL(glFramebufferTexture1D);
			BindOpenGL(glFramebufferTexture2D);
			BindOpenGL(glFramebufferTexture3D);
			BindOpenGL(glFramebufferRenderbuffer);
			BindOpenGL(glGetFramebufferAttachmentParameteriv);
			BindOpenGL(glGenerateMipmap);
			BindOpenGL(glBlitFramebuffer);
			BindOpenGL(glRenderbufferStorageMultisample);
			BindOpenGL(glFramebufferTextureLayer);
			BindOpenGL(glMapBufferRange);
			BindOpenGL(glFlushMappedBufferRange);
			BindOpenGL(glBindVertexArray);
			BindOpenGL(glDeleteVertexArrays);
			BindOpenGL(glGenVertexArrays);
			BindOpenGL(glIsVertexArray);

			// 3.1
			BindOpenGL(glDrawArraysInstanced);
			BindOpenGL(glDrawElementsInstanced);
			BindOpenGL(glTexBuffer);
			BindOpenGL(glPrimitiveRestartIndex);
			BindOpenGL(glCopyBufferSubData);
			BindOpenGL(glGetUniformIndices);
			BindOpenGL(glGetActiveUniformsiv);
			BindOpenGL(glGetActiveUniformName);
			BindOpenGL(glGetUniformBlockIndex);
			BindOpenGL(glGetActiveUniformBlockiv);
			BindOpenGL(glGetActiveUniformBlockName);
			BindOpenGL(glUniformBlockBinding);

			// 3.2
			BindOpenGL(glDrawElementsBaseVertex);
			BindOpenGL(glDrawRangeElementsBaseVertex);
			BindOpenGL(glDrawElementsInstancedBaseVertex);
			BindOpenGL(glMultiDrawElementsBaseVertex);
			BindOpenGL(glProvokingVertex);
			BindOpenGL(glFenceSync);
			BindOpenGL(glIsSync);
			BindOpenGL(glDeleteSync);
			BindOpenGL(glClientWaitSync);
			BindOpenGL(glWaitSync);
			BindOpenGL(glGetInteger64v);
			BindOpenGL(glGetSynciv);
			BindOpenGL(glGetInteger64i_v);
			BindOpenGL(glGetBufferParameteri64v);
			BindOpenGL(glFramebufferTexture);
			BindOpenGL(glTexImage2DMultisample);
			BindOpenGL(glTexImage3DMultisample);
			BindOpenGL(glGetMultisamplefv);
			BindOpenGL(glSampleMaski);
		}

		if(version >= gl::Version::Core4_1)
		{
			// 3.3
			BindOpenGL(glBindFragDataLocationIndexed);
			BindOpenGL(glGetFragDataIndex);
			BindOpenGL(glGenSamplers);
			BindOpenGL(glDeleteSamplers);
			BindOpenGL(glIsSampler);
			BindOpenGL(glBindSampler);
			BindOpenGL(glSamplerParameteri);
			BindOpenGL(glSamplerParameteriv);
			BindOpenGL(glSamplerParameterf);
			BindOpenGL(glSamplerParameterfv);
			BindOpenGL(glSamplerParameterIiv);
			BindOpenGL(glSamplerParameterIuiv);
			BindOpenGL(glGetSamplerParameteriv);
			BindOpenGL(glGetSamplerParameterIiv);
			BindOpenGL(glGetSamplerParameterfv);
			BindOpenGL(glGetSamplerParameterIuiv);
			BindOpenGL(glQueryCounter);
			BindOpenGL(glGetQueryObjecti64v);
			BindOpenGL(glGetQueryObjectui64v);
			BindOpenGL(glVertexAttribDivisor);
			BindOpenGL(glVertexAttribP1ui);
			BindOpenGL(glVertexAttribP1uiv);
			BindOpenGL(glVertexAttribP2ui);
			BindOpenGL(glVertexAttribP2uiv);
			BindOpenGL(glVertexAttribP3ui);
			BindOpenGL(glVertexAttribP3uiv);
			BindOpenGL(glVertexAttribP4ui);
			BindOpenGL(glVertexAttribP4uiv);

			// 4.0
			BindOpenGL(glMinSampleShading);
			BindOpenGL(glBlendEquationi);
			BindOpenGL(glBlendEquationSeparatei);
			BindOpenGL(glBlendFunci);
			BindOpenGL(glBlendFuncSeparatei);
			BindOpenGL(glDrawArraysIndirect);
			BindOpenGL(glDrawElementsIndirect);
			BindOpenGL(glUniform1d);
			BindOpenGL(glUniform2d);
			BindOpenGL(glUniform3d);
			BindOpenGL(glUniform4d);
			BindOpenGL(glUniform1dv);
			BindOpenGL(glUniform2dv);
			BindOpenGL(glUniform3dv);
			BindOpenGL(glUniform4dv);
			BindOpenGL(glUniformMatrix2dv);
			BindOpenGL(glUniformMatrix3dv);
			BindOpenGL(glUniformMatrix4dv);
			BindOpenGL(glUniformMatrix2x3dv);
			BindOpenGL(glUniformMatrix2x4dv);
			BindOpenGL(glUniformMatrix3x2dv);
			BindOpenGL(glUniformMatrix3x4dv);
			BindOpenGL(glUniformMatrix4x2dv);
			BindOpenGL(glUniformMatrix4x3dv);
			BindOpenGL(glGetUniformdv);
			BindOpenGL(glGetSubroutineUniformLocation);
			BindOpenGL(glGetSubroutineIndex);
			BindOpenGL(glGetActiveSubroutineUniformiv);
			BindOpenGL(glGetActiveSubroutineUniformName);
			BindOpenGL(glGetActiveSubroutineName);
			BindOpenGL(glUniformSubroutinesuiv);
			BindOpenGL(glGetUniformSubroutineuiv);
			BindOpenGL(glGetProgramStageiv);
			BindOpenGL(glPatchParameteri);
			BindOpenGL(glPatchParameterfv);
			BindOpenGL(glBindTransformFeedback);
			BindOpenGL(glDeleteTransformFeedbacks);
			BindOpenGL(glGenTransformFeedbacks);
			BindOpenGL(glIsTransformFeedback);
			BindOpenGL(glPauseTransformFeedback);
			BindOpenGL(glResumeTransformFeedback);
			BindOpenGL(glDrawTransformFeedback);
			BindOpenGL(glDrawTransformFeedbackStream);
			BindOpenGL(glBeginQueryIndexed);
			BindOpenGL(glEndQueryIndexed);
			BindOpenGL(glGetQueryIndexediv);

			// 4.1
			BindOpenGL(glReleaseShaderCompiler);
			BindOpenGL(glShaderBinary);
			BindOpenGL(glGetShaderPrecisionFormat);
			BindOpenGL(glDepthRangef);
			BindOpenGL(glClearDepthf);
			BindOpenGL(glGetProgramBinary);
			BindOpenGL(glProgramBinary);
			BindOpenGL(glProgramParameteri);
			BindOpenGL(glUseProgramStages);
			BindOpenGL(glActiveShaderProgram);
			BindOpenGL(glCreateShaderProgramv);
			BindOpenGL(glBindProgramPipeline);
			BindOpenGL(glDeleteProgramPipelines);
			BindOpenGL(glGenProgramPipelines);
			BindOpenGL(glIsProgramPipeline);
			BindOpenGL(glGetProgramPipelineiv);
			BindOpenGL(glProgramUniform1i);
			BindOpenGL(glProgramUniform1iv);
			BindOpenGL(glProgramUniform1f);
			BindOpenGL(glProgramUniform1fv);
			BindOpenGL(glProgramUniform1d);
			BindOpenGL(glProgramUniform1dv);
			BindOpenGL(glProgramUniform1ui);
			BindOpenGL(glProgramUniform1uiv);
			BindOpenGL(glProgramUniform2i);
			BindOpenGL(glProgramUniform2iv);
			BindOpenGL(glProgramUniform2f);
			BindOpenGL(glProgramUniform2fv);
			BindOpenGL(glProgramUniform2d);
			BindOpenGL(glProgramUniform2dv);
			BindOpenGL(glProgramUniform2ui);
			BindOpenGL(glProgramUniform2uiv);
			BindOpenGL(glProgramUniform3i);
			BindOpenGL(glProgramUniform3iv);
			BindOpenGL(glProgramUniform3f);
			BindOpenGL(glProgramUniform3fv);
			BindOpenGL(glProgramUniform3d);
			BindOpenGL(glProgramUniform3dv);
			BindOpenGL(glProgramUniform3ui);
			BindOpenGL(glProgramUniform3uiv);
			BindOpenGL(glProgramUniform4i);
			BindOpenGL(glProgramUniform4iv);
			BindOpenGL(glProgramUniform4f);
			BindOpenGL(glProgramUniform4fv);
			BindOpenGL(glProgramUniform4d);
			BindOpenGL(glProgramUniform4dv);
			BindOpenGL(glProgramUniform4ui);
			BindOpenGL(glProgramUniform4uiv);
			BindOpenGL(glProgramUniformMatrix2fv);
			BindOpenGL(glProgramUniformMatrix3fv);
			BindOpenGL(glProgramUniformMatrix4fv);
			BindOpenGL(glProgramUniformMatrix2dv);
			BindOpenGL(glProgramUniformMatrix3dv);
			BindOpenGL(glProgramUniformMatrix4dv);
			BindOpenGL(glProgramUniformMatrix2x3fv);
			BindOpenGL(glProgramUniformMatrix3x2fv);
			BindOpenGL(glProgramUniformMatrix2x4fv);
			BindOpenGL(glProgramUniformMatrix4x2fv);
			BindOpenGL(glProgramUniformMatrix3x4fv);
			BindOpenGL(glProgramUniformMatrix4x3fv);
			BindOpenGL(glProgramUniformMatrix2x3dv);
			BindOpenGL(glProgramUniformMatrix3x2dv);
			BindOpenGL(glProgramUniformMatrix2x4dv);
			BindOpenGL(glProgramUniformMatrix4x2dv);
			BindOpenGL(glProgramUniformMatrix3x4dv);
			BindOpenGL(glProgramUniformMatrix4x3dv);
			BindOpenGL(glValidateProgramPipeline);
			BindOpenGL(glGetProgramPipelineInfoLog);
			BindOpenGL(glVertexAttribL1d);
			BindOpenGL(glVertexAttribL2d);
			BindOpenGL(glVertexAttribL3d);
			BindOpenGL(glVertexAttribL4d);
			BindOpenGL(glVertexAttribL1dv);
			BindOpenGL(glVertexAttribL2dv);
			BindOpenGL(glVertexAttribL3dv);
			BindOpenGL(glVertexAttribL4dv);
			BindOpenGL(glVertexAttribLPointer);
			BindOpenGL(glGetVertexAttribLdv);
			BindOpenGL(glViewportArrayv);
			BindOpenGL(glViewportIndexedf);
			BindOpenGL(glViewportIndexedfv);
			BindOpenGL(glScissorArrayv);
			BindOpenGL(glScissorIndexed);
			BindOpenGL(glScissorIndexedv);
			BindOpenGL(glDepthRangeArrayv);
			BindOpenGL(glDepthRangeIndexed);
			BindOpenGL(glGetFloati_v);
			BindOpenGL(glGetDoublei_v);
		}
	}
	
	void BindOpenGLExtensions(gl::Version version)
	{
		if(version < gl::Version::Core4_1)
		{
			if(gl::SupportsFeature(gl::Feature::ShaderBinary))
			{
				BindOpenGL(glGetProgramBinary);
				BindOpenGL(glProgramBinary);
				BindOpenGL(glProgramParameteri);
			}
		}
	}
}
