//
//  RNOpenGL.h
//  Rayne
//
//  Copyright 2014 by Überpixel. All rights reserved.
//  Unauthorized use is punishable by torture, mutilation, and vivisection.
//

#ifndef __RAYNE_OPENGL_H__
#define __RAYNE_OPENGL_H__

#include <string>
#include "RNDefines.h"

// OpenGL is a moving target, so is Rayne
// We don't rely on system headers which might be outdated, but we rely on whatever the graphics card tells us
#if RN_TARGET_OPENGL

	#if RN_PLATFORM_MAC_OS
		// This is by far the worst OpenGL hack. Ever.
		// Cocoa.h pulls OpenGL in which fucks up everything from glcorearb.h. So yeah, dirty hacks all around
		#if defined(__gl_h_) || defined(__glext_h_)
			#undef GL_VERSION_1_1
			#undef GL_VERSION_1_2
			#undef GL_VERSION_1_3
			#undef GL_VERSION_1_4
			#undef GL_VERSION_1_5
			#undef GL_VERSION_2_0
			#undef GL_VERSION_2_1
			#undef GL_VERSION_3_0
			#undef GL_VERSION_3_1
			#undef GL_VERSION_3_2
			#undef GL_VERSION_3_3
			#undef GL_VERSION_4_0
			#undef GL_VERSION_4_1
			#undef GL_VERSION_4_2
			#undef GL_VERSION_4_3
			#undef GL_VERSION_4_4

			#undef GL_DRAW_FRAMEBUFFER_BINDING
			#undef GL_GLEXT_VERSION

			#undef __gl_h_
			#undef __glext_h_
		#endif
	#endif

	#if RN_PLATFORM_MAC_OS
		#include "glcorearb.h"
		#include "glext.h"
	#else
		#include "ogl/glcorearb.h"
		#include "ogl/glext.h"
	#endif

	#if RN_PLATFORM_WINDOWS
		#include "ogl/wglext.h"

		#pragma comment(lib, "opengl32.lib")
	#endif
#endif

#ifndef RN_BUILD_DEBUG
	#define RN_CHECKOPENGL() RN::gl::CheckForError(__FILE__, __LINE__)
	#define RN_CHECKOPENGL_AGGRESSIVE() RN::gl::CheckForError(__FILE__, __LINE__)
#else
	#define RN_CHECKOPENGL() RN::gl::CheckForError(__FILE__, __LINE__)
	#define RN_CHECKOPENGL_AGGRESSIVE() (void)0
#endif

namespace RN
{
	namespace gl
	{
		enum class Version : int
		{
#if RN_TARGET_OPENGL_ES
			ES2,
#endif
#if RN_TARGET_OPENGL
			Core3_2,
			Core4_1
#endif
		};
		
		enum class Feature : int
		{
			VertexArrays,
			GeometryShaders,
			TessellationShaders,
			AnisotropicFilter,
			ShaderBinary,
			ProgramValidation
		};
		
		Version MaximumVersion();
		Version WantedVersion();
		
		void CheckForError(const char *file, int line);
		bool SupportsFeature(Feature feature);
		bool SupportsExtensions(const std::string& extension);

		// 1.0
		extern RNAPI PFNGLCULLFACEPROC CullFace;
		extern RNAPI PFNGLFRONTFACEPROC FrontFace;
		extern RNAPI PFNGLHINTPROC Hint;
		extern RNAPI PFNGLLINEWIDTHPROC LineWidth;
		extern RNAPI PFNGLPOINTSIZEPROC PointSize;
		extern RNAPI PFNGLPOLYGONMODEPROC PolygonMode;
		extern RNAPI PFNGLSCISSORPROC Scissor;
		extern RNAPI PFNGLTEXPARAMETERFPROC TexParameterf;
		extern RNAPI PFNGLTEXPARAMETERFVPROC TexParameterfv;
		extern RNAPI PFNGLTEXPARAMETERIPROC TexParameteri;
		extern RNAPI PFNGLTEXPARAMETERIVPROC TexParameteriv;
		extern RNAPI PFNGLTEXIMAGE1DPROC TexImage1D;
		extern RNAPI PFNGLTEXIMAGE2DPROC TexImage2D;
		extern RNAPI PFNGLDRAWBUFFERPROC DrawBuffer;
		extern RNAPI PFNGLCLEARPROC Clear;
		extern RNAPI PFNGLCLEARCOLORPROC ClearColor;
		extern RNAPI PFNGLCLEARSTENCILPROC ClearStencil;
		extern RNAPI PFNGLCLEARDEPTHPROC ClearDepth;
		extern RNAPI PFNGLSTENCILMASKPROC StencilMask;
		extern RNAPI PFNGLCOLORMASKPROC ColorMask;
		extern RNAPI PFNGLDEPTHMASKPROC DepthMask;
		extern RNAPI PFNGLDISABLEPROC Disable;
		extern RNAPI PFNGLENABLEPROC Enable;
		extern RNAPI PFNGLFINISHPROC Finish;
		extern RNAPI PFNGLFLUSHPROC Flush;
		extern RNAPI PFNGLBLENDFUNCPROC BlendFunc;
		extern RNAPI PFNGLLOGICOPPROC LogicOp;
		extern RNAPI PFNGLSTENCILFUNCPROC StencilFunc;
		extern RNAPI PFNGLSTENCILOPPROC StencilOp;
		extern RNAPI PFNGLDEPTHFUNCPROC DepthFunc;
		extern RNAPI PFNGLPIXELSTOREFPROC PixelStoref;
		extern RNAPI PFNGLPIXELSTOREIPROC PixelStorei;
		extern RNAPI PFNGLREADBUFFERPROC ReadBuffer;
		extern RNAPI PFNGLREADPIXELSPROC ReadPixels;
		extern RNAPI PFNGLGETBOOLEANVPROC GetBooleanv;
		extern RNAPI PFNGLGETDOUBLEVPROC GetDoublev;
		extern RNAPI PFNGLGETERRORPROC GetError;
		extern RNAPI PFNGLGETFLOATVPROC GetFloatv;
		extern RNAPI PFNGLGETINTEGERVPROC GetIntegerv;
		extern RNAPI PFNGLGETSTRINGPROC GetString;
		extern RNAPI PFNGLGETTEXIMAGEPROC GetTexImage;
		extern RNAPI PFNGLGETTEXPARAMETERFVPROC GetTexParameterfv;
		extern RNAPI PFNGLGETTEXPARAMETERIVPROC GetTexParameteriv;
		extern RNAPI PFNGLGETTEXLEVELPARAMETERFVPROC GetTexLevelParameterfv;
		extern RNAPI PFNGLGETTEXLEVELPARAMETERIVPROC GetTexLevelParameteriv;
		extern RNAPI PFNGLISENABLEDPROC IsEnabled;
		extern RNAPI PFNGLDEPTHRANGEPROC DepthRange;
		extern RNAPI PFNGLVIEWPORTPROC Viewport;

		// 1.1
		extern RNAPI PFNGLDRAWARRAYSPROC DrawArrays;
		extern RNAPI PFNGLDRAWELEMENTSPROC DrawElements;
		extern RNAPI PFNGLGETPOINTERVPROC GetPointerv;
		extern RNAPI PFNGLPOLYGONOFFSETPROC PolygonOffset;
		extern RNAPI PFNGLCOPYTEXIMAGE1DPROC CopyTexImage1D;
		extern RNAPI PFNGLCOPYTEXIMAGE2DPROC CopyTexImage2D;
		extern RNAPI PFNGLCOPYTEXSUBIMAGE1DPROC CopyTexSubImage1D;
		extern RNAPI PFNGLCOPYTEXSUBIMAGE2DPROC CopyTexSubImage2D;
		extern RNAPI PFNGLTEXSUBIMAGE1DPROC TexSubImage1D;
		extern RNAPI PFNGLTEXSUBIMAGE2DPROC TexSubImage2D;
		extern RNAPI PFNGLBINDTEXTUREPROC BindTexture;
		extern RNAPI PFNGLDELETETEXTURESPROC DeleteTextures;
		extern RNAPI PFNGLGENTEXTURESPROC GenTextures;
		extern RNAPI PFNGLISTEXTUREPROC IsTexture;

		// 1.2
		extern RNAPI PFNGLDRAWRANGEELEMENTSPROC DrawRangeElements;
		extern RNAPI PFNGLTEXIMAGE3DPROC TexImage3D;
		extern RNAPI PFNGLTEXSUBIMAGE3DPROC TexSubImage3D;
		extern RNAPI PFNGLCOPYTEXSUBIMAGE3DPROC CopyTexSubImage3D;

		// 1.3
		extern RNAPI PFNGLACTIVETEXTUREPROC ActiveTexture;
		extern RNAPI PFNGLSAMPLECOVERAGEPROC SampleCoverage;
		extern RNAPI PFNGLCOMPRESSEDTEXIMAGE3DPROC CompressedTexImage3D;
		extern RNAPI PFNGLCOMPRESSEDTEXIMAGE2DPROC CompressedTexImage2D;
		extern RNAPI PFNGLCOMPRESSEDTEXIMAGE1DPROC CompressedTexImage1D;
		extern RNAPI PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC CompressedTexSubImage3D;
		extern RNAPI PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC CompressedTexSubImage2D;
		extern RNAPI PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC CompressedTexSubImage1D;
		extern RNAPI PFNGLGETCOMPRESSEDTEXIMAGEPROC GetCompressedTexImage;

		// 1.4
		extern RNAPI PFNGLBLENDFUNCSEPARATEPROC BlendFuncSeparate;
		extern RNAPI PFNGLMULTIDRAWARRAYSPROC MultiDrawArrays;
		extern RNAPI PFNGLMULTIDRAWELEMENTSPROC MultiDrawElements;
		extern RNAPI PFNGLPOINTPARAMETERFPROC PointParameterf;
		extern RNAPI PFNGLPOINTPARAMETERFVPROC PointParameterfv;
		extern RNAPI PFNGLPOINTPARAMETERIPROC PointParameteri;
		extern RNAPI PFNGLPOINTPARAMETERIVPROC PointParameteriv;
		extern RNAPI PFNGLBLENDCOLORPROC BlendColor;
		extern RNAPI PFNGLBLENDEQUATIONPROC BlendEquation;

		// 1.5
		extern RNAPI PFNGLGENQUERIESPROC GenQueries;
		extern RNAPI PFNGLDELETEQUERIESPROC DeleteQueries;
		extern RNAPI PFNGLISQUERYPROC IsQuery;
		extern RNAPI PFNGLBEGINQUERYPROC BeginQuery;
		extern RNAPI PFNGLENDQUERYPROC EndQuery;
		extern RNAPI PFNGLGETQUERYIVPROC GetQueryiv;
		extern RNAPI PFNGLGETQUERYOBJECTIVPROC GetQueryObjectiv;
		extern RNAPI PFNGLGETQUERYOBJECTUIVPROC GetQueryObjectuiv;
		extern RNAPI PFNGLBINDBUFFERPROC BindBuffer;
		extern RNAPI PFNGLDELETEBUFFERSPROC DeleteBuffers;
		extern RNAPI PFNGLGENBUFFERSPROC GenBuffers;
		extern RNAPI PFNGLISBUFFERPROC IsBuffer;
		extern RNAPI PFNGLBUFFERDATAPROC BufferData;
		extern RNAPI PFNGLBUFFERSUBDATAPROC BufferSubData;
		extern RNAPI PFNGLGETBUFFERSUBDATAPROC GetBufferSubData;
		extern RNAPI PFNGLMAPBUFFERPROC MapBuffer;
		extern RNAPI PFNGLUNMAPBUFFERPROC UnmapBuffer;
		extern RNAPI PFNGLGETBUFFERPARAMETERIVPROC GetBufferParameteriv;
		extern RNAPI PFNGLGETBUFFERPOINTERVPROC GetBufferPointerv;

		// 2.0
		extern RNAPI PFNGLBLENDEQUATIONSEPARATEPROC BlendEquationSeparate;
		extern RNAPI PFNGLDRAWBUFFERSPROC DrawBuffers;
		extern RNAPI PFNGLSTENCILOPSEPARATEPROC StencilOpSeparate;
		extern RNAPI PFNGLSTENCILFUNCSEPARATEPROC StencilFuncSeparate;
		extern RNAPI PFNGLSTENCILMASKSEPARATEPROC StencilMaskSeparate;
		extern RNAPI PFNGLATTACHSHADERPROC AttachShader;
		extern RNAPI PFNGLBINDATTRIBLOCATIONPROC BindAttribLocation;
		extern RNAPI PFNGLCOMPILESHADERPROC CompileShader;
		extern RNAPI PFNGLCREATEPROGRAMPROC CreateProgram;
		extern RNAPI PFNGLCREATESHADERPROC CreateShader;
		extern RNAPI PFNGLDELETEPROGRAMPROC DeleteProgram;
		extern RNAPI PFNGLDELETESHADERPROC DeleteShader;
		extern RNAPI PFNGLDETACHSHADERPROC DetachShader;
		extern RNAPI PFNGLDISABLEVERTEXATTRIBARRAYPROC DisableVertexAttribArray;
		extern RNAPI PFNGLENABLEVERTEXATTRIBARRAYPROC EnableVertexAttribArray;
		extern RNAPI PFNGLGETACTIVEATTRIBPROC GetActiveAttrib;
		extern RNAPI PFNGLGETACTIVEUNIFORMPROC GetActiveUniform;
		extern RNAPI PFNGLGETATTACHEDSHADERSPROC GetAttachedShaders;
		extern RNAPI PFNGLGETATTRIBLOCATIONPROC GetAttribLocation;
		extern RNAPI PFNGLGETPROGRAMIVPROC GetProgramiv;
		extern RNAPI PFNGLGETPROGRAMINFOLOGPROC GetProgramInfoLog;
		extern RNAPI PFNGLGETSHADERIVPROC GetShaderiv;
		extern RNAPI PFNGLGETSHADERINFOLOGPROC GetShaderInfoLog;
		extern RNAPI PFNGLGETSHADERSOURCEPROC GetShaderSource;
		extern RNAPI PFNGLGETUNIFORMLOCATIONPROC GetUniformLocation;
		extern RNAPI PFNGLGETUNIFORMFVPROC GetUniformfv;
		extern RNAPI PFNGLGETUNIFORMIVPROC GetUniformiv;
		extern RNAPI PFNGLGETVERTEXATTRIBDVPROC GetVertexAttribdv;
		extern RNAPI PFNGLGETVERTEXATTRIBFVPROC GetVertexAttribfv;
		extern RNAPI PFNGLGETVERTEXATTRIBIVPROC GetVertexAttribiv;
		extern RNAPI PFNGLGETVERTEXATTRIBPOINTERVPROC GetVertexAttribPointerv;
		extern RNAPI PFNGLISPROGRAMPROC IsProgram;
		extern RNAPI PFNGLISSHADERPROC IsShader;
		extern RNAPI PFNGLLINKPROGRAMPROC LinkProgram;
		extern RNAPI PFNGLSHADERSOURCEPROC ShaderSource;
		extern RNAPI PFNGLUSEPROGRAMPROC UseProgram;
		extern RNAPI PFNGLUNIFORM1FPROC Uniform1f;
		extern RNAPI PFNGLUNIFORM2FPROC Uniform2f;
		extern RNAPI PFNGLUNIFORM3FPROC Uniform3f;
		extern RNAPI PFNGLUNIFORM4FPROC Uniform4f;
		extern RNAPI PFNGLUNIFORM1IPROC Uniform1i;
		extern RNAPI PFNGLUNIFORM2IPROC Uniform2i;
		extern RNAPI PFNGLUNIFORM3IPROC Uniform3i;
		extern RNAPI PFNGLUNIFORM4IPROC Uniform4i;
		extern RNAPI PFNGLUNIFORM1FVPROC Uniform1fv;
		extern RNAPI PFNGLUNIFORM2FVPROC Uniform2fv;
		extern RNAPI PFNGLUNIFORM3FVPROC Uniform3fv;
		extern RNAPI PFNGLUNIFORM4FVPROC Uniform4fv;
		extern RNAPI PFNGLUNIFORM1IVPROC Uniform1iv;
		extern RNAPI PFNGLUNIFORM2IVPROC Uniform2iv;
		extern RNAPI PFNGLUNIFORM3IVPROC Uniform3iv;
		extern RNAPI PFNGLUNIFORM4IVPROC Uniform4iv;
		extern RNAPI PFNGLUNIFORMMATRIX2FVPROC UniformMatrix2fv;
		extern RNAPI PFNGLUNIFORMMATRIX3FVPROC UniformMatrix3fv;
		extern RNAPI PFNGLUNIFORMMATRIX4FVPROC UniformMatrix4fv;
		extern RNAPI PFNGLVALIDATEPROGRAMPROC ValidateProgram;
		extern RNAPI PFNGLVERTEXATTRIB1DPROC VertexAttrib1d;
		extern RNAPI PFNGLVERTEXATTRIB1DVPROC VertexAttrib1dv;
		extern RNAPI PFNGLVERTEXATTRIB1FPROC VertexAttrib1f;
		extern RNAPI PFNGLVERTEXATTRIB1FVPROC VertexAttrib1fv;
		extern RNAPI PFNGLVERTEXATTRIB1SPROC VertexAttrib1s;
		extern RNAPI PFNGLVERTEXATTRIB1SVPROC VertexAttrib1sv;
		extern RNAPI PFNGLVERTEXATTRIB2DPROC VertexAttrib2d;
		extern RNAPI PFNGLVERTEXATTRIB2DVPROC VertexAttrib2dv;
		extern RNAPI PFNGLVERTEXATTRIB2FPROC VertexAttrib2f;
		extern RNAPI PFNGLVERTEXATTRIB2FVPROC VertexAttrib2fv;
		extern RNAPI PFNGLVERTEXATTRIB2SPROC VertexAttrib2s;
		extern RNAPI PFNGLVERTEXATTRIB2SVPROC VertexAttrib2sv;
		extern RNAPI PFNGLVERTEXATTRIB3DPROC VertexAttrib3d;
		extern RNAPI PFNGLVERTEXATTRIB3DVPROC VertexAttrib3dv;
		extern RNAPI PFNGLVERTEXATTRIB3FPROC VertexAttrib3f;
		extern RNAPI PFNGLVERTEXATTRIB3FVPROC VertexAttrib3fv;
		extern RNAPI PFNGLVERTEXATTRIB3SPROC VertexAttrib3s;
		extern RNAPI PFNGLVERTEXATTRIB3SVPROC VertexAttrib3sv;
		extern RNAPI PFNGLVERTEXATTRIB4NBVPROC VertexAttrib4Nbv;
		extern RNAPI PFNGLVERTEXATTRIB4NIVPROC VertexAttrib4Niv;
		extern RNAPI PFNGLVERTEXATTRIB4NSVPROC VertexAttrib4Nsv;
		extern RNAPI PFNGLVERTEXATTRIB4NUBPROC VertexAttrib4Nub;
		extern RNAPI PFNGLVERTEXATTRIB4NUBVPROC VertexAttrib4Nubv;
		extern RNAPI PFNGLVERTEXATTRIB4NUIVPROC VertexAttrib4Nuiv;
		extern RNAPI PFNGLVERTEXATTRIB4NUSVPROC VertexAttrib4Nusv;
		extern RNAPI PFNGLVERTEXATTRIB4BVPROC VertexAttrib4bv;
		extern RNAPI PFNGLVERTEXATTRIB4DPROC VertexAttrib4d;
		extern RNAPI PFNGLVERTEXATTRIB4DVPROC VertexAttrib4dv;
		extern RNAPI PFNGLVERTEXATTRIB4FPROC VertexAttrib4f;
		extern RNAPI PFNGLVERTEXATTRIB4FVPROC VertexAttrib4fv;
		extern RNAPI PFNGLVERTEXATTRIB4IVPROC VertexAttrib4iv;
		extern RNAPI PFNGLVERTEXATTRIB4SPROC VertexAttrib4s;
		extern RNAPI PFNGLVERTEXATTRIB4SVPROC VertexAttrib4sv;
		extern RNAPI PFNGLVERTEXATTRIB4UBVPROC VertexAttrib4ubv;
		extern RNAPI PFNGLVERTEXATTRIB4UIVPROC VertexAttrib4uiv;
		extern RNAPI PFNGLVERTEXATTRIB4USVPROC VertexAttrib4usv;
		extern RNAPI PFNGLVERTEXATTRIBPOINTERPROC VertexAttribPointer;

		// 2.1
		extern RNAPI PFNGLUNIFORMMATRIX2X3FVPROC UniformMatrix2x3fv;
		extern RNAPI PFNGLUNIFORMMATRIX3X2FVPROC UniformMatrix3x2fv;
		extern RNAPI PFNGLUNIFORMMATRIX2X4FVPROC UniformMatrix2x4fv;
		extern RNAPI PFNGLUNIFORMMATRIX4X2FVPROC UniformMatrix4x2fv;
		extern RNAPI PFNGLUNIFORMMATRIX3X4FVPROC UniformMatrix3x4fv;
		extern RNAPI PFNGLUNIFORMMATRIX4X3FVPROC UniformMatrix4x3fv;

		// 3.0
		extern RNAPI PFNGLCOLORMASKIPROC ColorMaski;
		extern RNAPI PFNGLGETBOOLEANI_VPROC GetBooleani_v;
		extern RNAPI PFNGLGETINTEGERI_VPROC GetIntegeri_v;
		extern RNAPI PFNGLENABLEIPROC Enablei;
		extern RNAPI PFNGLDISABLEIPROC Disablei;
		extern RNAPI PFNGLISENABLEDIPROC IsEnabledi;
		extern RNAPI PFNGLBEGINTRANSFORMFEEDBACKPROC BeginTransformFeedback;
		extern RNAPI PFNGLENDTRANSFORMFEEDBACKPROC EndTransformFeedback;
		extern RNAPI PFNGLBINDBUFFERRANGEPROC BindBufferRange;
		extern RNAPI PFNGLBINDBUFFERBASEPROC BindBufferBase;
		extern RNAPI PFNGLTRANSFORMFEEDBACKVARYINGSPROC TransformFeedbackVaryings;
		extern RNAPI PFNGLGETTRANSFORMFEEDBACKVARYINGPROC GetTransformFeedbackVarying;
		extern RNAPI PFNGLCLAMPCOLORPROC ClampColor;
		extern RNAPI PFNGLBEGINCONDITIONALRENDERPROC BeginConditionalRender;
		extern RNAPI PFNGLENDCONDITIONALRENDERPROC EndConditionalRender;
		extern RNAPI PFNGLVERTEXATTRIBIPOINTERPROC VertexAttribIPointer;
		extern RNAPI PFNGLGETVERTEXATTRIBIIVPROC GetVertexAttribIiv;
		extern RNAPI PFNGLGETVERTEXATTRIBIUIVPROC GetVertexAttribIuiv;
		extern RNAPI PFNGLVERTEXATTRIBI1IPROC VertexAttribI1i;
		extern RNAPI PFNGLVERTEXATTRIBI2IPROC VertexAttribI2i;
		extern RNAPI PFNGLVERTEXATTRIBI3IPROC VertexAttribI3i;
		extern RNAPI PFNGLVERTEXATTRIBI4IPROC VertexAttribI4i;
		extern RNAPI PFNGLVERTEXATTRIBI1UIPROC VertexAttribI1ui;
		extern RNAPI PFNGLVERTEXATTRIBI2UIPROC VertexAttribI2ui;
		extern RNAPI PFNGLVERTEXATTRIBI3UIPROC VertexAttribI3ui;
		extern RNAPI PFNGLVERTEXATTRIBI4UIPROC VertexAttribI4ui;
		extern RNAPI PFNGLVERTEXATTRIBI1IVPROC VertexAttribI1iv;
		extern RNAPI PFNGLVERTEXATTRIBI2IVPROC VertexAttribI2iv;
		extern RNAPI PFNGLVERTEXATTRIBI3IVPROC VertexAttribI3iv;
		extern RNAPI PFNGLVERTEXATTRIBI4IVPROC VertexAttribI4iv;
		extern RNAPI PFNGLVERTEXATTRIBI1UIVPROC VertexAttribI1uiv;
		extern RNAPI PFNGLVERTEXATTRIBI2UIVPROC VertexAttribI2uiv;
		extern RNAPI PFNGLVERTEXATTRIBI3UIVPROC VertexAttribI3uiv;
		extern RNAPI PFNGLVERTEXATTRIBI4UIVPROC VertexAttribI4uiv;
		extern RNAPI PFNGLVERTEXATTRIBI4BVPROC VertexAttribI4bv;
		extern RNAPI PFNGLVERTEXATTRIBI4SVPROC VertexAttribI4sv;
		extern RNAPI PFNGLVERTEXATTRIBI4UBVPROC VertexAttribI4ubv;
		extern RNAPI PFNGLVERTEXATTRIBI4USVPROC VertexAttribI4usv;
		extern RNAPI PFNGLGETUNIFORMUIVPROC GetUniformuiv;
		extern RNAPI PFNGLBINDFRAGDATALOCATIONPROC BindFragDataLocation;
		extern RNAPI PFNGLGETFRAGDATALOCATIONPROC GetFragDataLocation;
		extern RNAPI PFNGLUNIFORM1UIPROC Uniform1ui;
		extern RNAPI PFNGLUNIFORM2UIPROC Uniform2ui;
		extern RNAPI PFNGLUNIFORM3UIPROC Uniform3ui;
		extern RNAPI PFNGLUNIFORM4UIPROC Uniform4ui;
		extern RNAPI PFNGLUNIFORM1UIVPROC Uniform1uiv;
		extern RNAPI PFNGLUNIFORM2UIVPROC Uniform2uiv;
		extern RNAPI PFNGLUNIFORM3UIVPROC Uniform3uiv;
		extern RNAPI PFNGLUNIFORM4UIVPROC Uniform4uiv;
		extern RNAPI PFNGLTEXPARAMETERIIVPROC TexParameterIiv;
		extern RNAPI PFNGLTEXPARAMETERIUIVPROC TexParameterIuiv;
		extern RNAPI PFNGLGETTEXPARAMETERIIVPROC GetTexParameterIiv;
		extern RNAPI PFNGLGETTEXPARAMETERIUIVPROC GetTexParameterIuiv;
		extern RNAPI PFNGLCLEARBUFFERIVPROC ClearBufferiv;
		extern RNAPI PFNGLCLEARBUFFERUIVPROC ClearBufferuiv;
		extern RNAPI PFNGLCLEARBUFFERFVPROC ClearBufferfv;
		extern RNAPI PFNGLCLEARBUFFERFIPROC ClearBufferfi;
		extern RNAPI PFNGLGETSTRINGIPROC GetStringi;
		extern RNAPI PFNGLISRENDERBUFFERPROC IsRenderbuffer;
		extern RNAPI PFNGLBINDRENDERBUFFERPROC BindRenderbuffer;
		extern RNAPI PFNGLDELETERENDERBUFFERSPROC DeleteRenderbuffers;
		extern RNAPI PFNGLGENRENDERBUFFERSPROC GenRenderbuffers;
		extern RNAPI PFNGLRENDERBUFFERSTORAGEPROC RenderbufferStorage;
		extern RNAPI PFNGLGETRENDERBUFFERPARAMETERIVPROC GetRenderbufferParameteriv;
		extern RNAPI PFNGLISFRAMEBUFFERPROC IsFramebuffer;
		extern RNAPI PFNGLBINDFRAMEBUFFERPROC BindFramebuffer;
		extern RNAPI PFNGLDELETEFRAMEBUFFERSPROC DeleteFramebuffers;
		extern RNAPI PFNGLGENFRAMEBUFFERSPROC GenFramebuffers;
		extern RNAPI PFNGLCHECKFRAMEBUFFERSTATUSPROC CheckFramebufferStatus;
		extern RNAPI PFNGLFRAMEBUFFERTEXTURE1DPROC FramebufferTexture1D;
		extern RNAPI PFNGLFRAMEBUFFERTEXTURE2DPROC FramebufferTexture2D;
		extern RNAPI PFNGLFRAMEBUFFERTEXTURE3DPROC FramebufferTexture3D;
		extern RNAPI PFNGLFRAMEBUFFERRENDERBUFFERPROC FramebufferRenderbuffer;
		extern RNAPI PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC GetFramebufferAttachmentParameteriv;
		extern RNAPI PFNGLGENERATEMIPMAPPROC GenerateMipmap;
		extern RNAPI PFNGLBLITFRAMEBUFFERPROC BlitFramebuffer;
		extern RNAPI PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC RenderbufferStorageMultisample;
		extern RNAPI PFNGLFRAMEBUFFERTEXTURELAYERPROC FramebufferTextureLayer;
		extern RNAPI PFNGLMAPBUFFERRANGEPROC MapBufferRange;
		extern RNAPI PFNGLFLUSHMAPPEDBUFFERRANGEPROC FlushMappedBufferRange;
		extern RNAPI PFNGLBINDVERTEXARRAYPROC BindVertexArray;
		extern RNAPI PFNGLDELETEVERTEXARRAYSPROC DeleteVertexArrays;
		extern RNAPI PFNGLGENVERTEXARRAYSPROC GenVertexArrays;
		extern RNAPI PFNGLISVERTEXARRAYPROC IsVertexArray;

		// 3.1
		extern RNAPI PFNGLDRAWARRAYSINSTANCEDPROC DrawArraysInstanced;
		extern RNAPI PFNGLDRAWELEMENTSINSTANCEDPROC DrawElementsInstanced;
		extern RNAPI PFNGLTEXBUFFERPROC TexBuffer;
		extern RNAPI PFNGLPRIMITIVERESTARTINDEXPROC PrimitiveRestartIndex;
		extern RNAPI PFNGLCOPYBUFFERSUBDATAPROC CopyBufferSubData;
		extern RNAPI PFNGLGETUNIFORMINDICESPROC GetUniformIndices;
		extern RNAPI PFNGLGETACTIVEUNIFORMSIVPROC GetActiveUniformsiv;
		extern RNAPI PFNGLGETACTIVEUNIFORMNAMEPROC GetActiveUniformName;
		extern RNAPI PFNGLGETUNIFORMBLOCKINDEXPROC GetUniformBlockIndex;
		extern RNAPI PFNGLGETACTIVEUNIFORMBLOCKIVPROC GetActiveUniformBlockiv;
		extern RNAPI PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC GetActiveUniformBlockName;
		extern RNAPI PFNGLUNIFORMBLOCKBINDINGPROC UniformBlockBinding;

		// 3.2
		extern RNAPI PFNGLDRAWELEMENTSBASEVERTEXPROC DrawElementsBaseVertex;
		extern RNAPI PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC DrawRangeElementsBaseVertex;
		extern RNAPI PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC DrawElementsInstancedBaseVertex;
		extern RNAPI PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC MultiDrawElementsBaseVertex;
		extern RNAPI PFNGLPROVOKINGVERTEXPROC ProvokingVertex;
		extern RNAPI PFNGLFENCESYNCPROC FenceSync;
		extern RNAPI PFNGLISSYNCPROC IsSync;
		extern RNAPI PFNGLDELETESYNCPROC DeleteSync;
		extern RNAPI PFNGLCLIENTWAITSYNCPROC ClientWaitSync;
		extern RNAPI PFNGLWAITSYNCPROC WaitSync;
		extern RNAPI PFNGLGETINTEGER64VPROC GetInteger64v;
		extern RNAPI PFNGLGETSYNCIVPROC GetSynciv;
		extern RNAPI PFNGLGETINTEGER64I_VPROC GetInteger64i_v;
		extern RNAPI PFNGLGETBUFFERPARAMETERI64VPROC GetBufferParameteri64v;
		extern RNAPI PFNGLFRAMEBUFFERTEXTUREPROC FramebufferTexture;
		extern RNAPI PFNGLTEXIMAGE2DMULTISAMPLEPROC TexImage2DMultisample;
		extern RNAPI PFNGLTEXIMAGE3DMULTISAMPLEPROC TexImage3DMultisample;
		extern RNAPI PFNGLGETMULTISAMPLEFVPROC GetMultisamplefv;
		extern RNAPI PFNGLSAMPLEMASKIPROC SampleMaski;

		// 3.3
		extern RNAPI PFNGLBINDFRAGDATALOCATIONINDEXEDPROC BindFragDataLocationIndexed;
		extern RNAPI PFNGLGETFRAGDATAINDEXPROC GetFragDataIndex;
		extern RNAPI PFNGLGENSAMPLERSPROC GenSamplers;
		extern RNAPI PFNGLDELETESAMPLERSPROC DeleteSamplers;
		extern RNAPI PFNGLISSAMPLERPROC IsSampler;
		extern RNAPI PFNGLBINDSAMPLERPROC BindSampler;
		extern RNAPI PFNGLSAMPLERPARAMETERIPROC SamplerParameteri;
		extern RNAPI PFNGLSAMPLERPARAMETERIVPROC SamplerParameteriv;
		extern RNAPI PFNGLSAMPLERPARAMETERFPROC SamplerParameterf;
		extern RNAPI PFNGLSAMPLERPARAMETERFVPROC SamplerParameterfv;
		extern RNAPI PFNGLSAMPLERPARAMETERIIVPROC SamplerParameterIiv;
		extern RNAPI PFNGLSAMPLERPARAMETERIUIVPROC SamplerParameterIuiv;
		extern RNAPI PFNGLGETSAMPLERPARAMETERIVPROC GetSamplerParameteriv;
		extern RNAPI PFNGLGETSAMPLERPARAMETERIIVPROC GetSamplerParameterIiv;
		extern RNAPI PFNGLGETSAMPLERPARAMETERFVPROC GetSamplerParameterfv;
		extern RNAPI PFNGLGETSAMPLERPARAMETERIUIVPROC GetSamplerParameterIuiv;
		extern RNAPI PFNGLQUERYCOUNTERPROC QueryCounter;
		extern RNAPI PFNGLGETQUERYOBJECTI64VPROC GetQueryObjecti64v;
		extern RNAPI PFNGLGETQUERYOBJECTUI64VPROC GetQueryObjectui64v;
		extern RNAPI PFNGLVERTEXATTRIBDIVISORPROC VertexAttribDivisor;
		extern RNAPI PFNGLVERTEXATTRIBP1UIPROC VertexAttribP1ui;
		extern RNAPI PFNGLVERTEXATTRIBP1UIVPROC VertexAttribP1uiv;
		extern RNAPI PFNGLVERTEXATTRIBP2UIPROC VertexAttribP2ui;
		extern RNAPI PFNGLVERTEXATTRIBP2UIVPROC VertexAttribP2uiv;
		extern RNAPI PFNGLVERTEXATTRIBP3UIPROC VertexAttribP3ui;
		extern RNAPI PFNGLVERTEXATTRIBP3UIVPROC VertexAttribP3uiv;
		extern RNAPI PFNGLVERTEXATTRIBP4UIPROC VertexAttribP4ui;
		extern RNAPI PFNGLVERTEXATTRIBP4UIVPROC VertexAttribP4uiv;

		// 4.0
		extern RNAPI PFNGLMINSAMPLESHADINGPROC MinSampleShading;
		extern RNAPI PFNGLBLENDEQUATIONIPROC BlendEquationi;
		extern RNAPI PFNGLBLENDEQUATIONSEPARATEIPROC BlendEquationSeparatei;
		extern RNAPI PFNGLBLENDFUNCIPROC BlendFunci;
		extern RNAPI PFNGLBLENDFUNCSEPARATEIPROC BlendFuncSeparatei;
		extern RNAPI PFNGLDRAWARRAYSINDIRECTPROC DrawArraysIndirect;
		extern RNAPI PFNGLDRAWELEMENTSINDIRECTPROC DrawElementsIndirect;
		extern RNAPI PFNGLUNIFORM1DPROC Uniform1d;
		extern RNAPI PFNGLUNIFORM2DPROC Uniform2d;
		extern RNAPI PFNGLUNIFORM3DPROC Uniform3d;
		extern RNAPI PFNGLUNIFORM4DPROC Uniform4d;
		extern RNAPI PFNGLUNIFORM1DVPROC Uniform1dv;
		extern RNAPI PFNGLUNIFORM2DVPROC Uniform2dv;
		extern RNAPI PFNGLUNIFORM3DVPROC Uniform3dv;
		extern RNAPI PFNGLUNIFORM4DVPROC Uniform4dv;
		extern RNAPI PFNGLUNIFORMMATRIX2DVPROC UniformMatrix2dv;
		extern RNAPI PFNGLUNIFORMMATRIX3DVPROC UniformMatrix3dv;
		extern RNAPI PFNGLUNIFORMMATRIX4DVPROC UniformMatrix4dv;
		extern RNAPI PFNGLUNIFORMMATRIX2X3DVPROC UniformMatrix2x3dv;
		extern RNAPI PFNGLUNIFORMMATRIX2X4DVPROC UniformMatrix2x4dv;
		extern RNAPI PFNGLUNIFORMMATRIX3X2DVPROC UniformMatrix3x2dv;
		extern RNAPI PFNGLUNIFORMMATRIX3X4DVPROC UniformMatrix3x4dv;
		extern RNAPI PFNGLUNIFORMMATRIX4X2DVPROC UniformMatrix4x2dv;
		extern RNAPI PFNGLUNIFORMMATRIX4X3DVPROC UniformMatrix4x3dv;
		extern RNAPI PFNGLGETUNIFORMDVPROC GetUniformdv;
		extern RNAPI PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC GetSubroutineUniformLocation;
		extern RNAPI PFNGLGETSUBROUTINEINDEXPROC GetSubroutineIndex;
		extern RNAPI PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC GetActiveSubroutineUniformiv;
		extern RNAPI PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC GetActiveSubroutineUniformName;
		extern RNAPI PFNGLGETACTIVESUBROUTINENAMEPROC GetActiveSubroutineName;
		extern RNAPI PFNGLUNIFORMSUBROUTINESUIVPROC UniformSubroutinesuiv;
		extern RNAPI PFNGLGETUNIFORMSUBROUTINEUIVPROC GetUniformSubroutineuiv;
		extern RNAPI PFNGLGETPROGRAMSTAGEIVPROC GetProgramStageiv;
		extern RNAPI PFNGLPATCHPARAMETERIPROC PatchParameteri;
		extern RNAPI PFNGLPATCHPARAMETERFVPROC PatchParameterfv;
		extern RNAPI PFNGLBINDTRANSFORMFEEDBACKPROC BindTransformFeedback;
		extern RNAPI PFNGLDELETETRANSFORMFEEDBACKSPROC DeleteTransformFeedbacks;
		extern RNAPI PFNGLGENTRANSFORMFEEDBACKSPROC GenTransformFeedbacks;
		extern RNAPI PFNGLISTRANSFORMFEEDBACKPROC IsTransformFeedback;
		extern RNAPI PFNGLPAUSETRANSFORMFEEDBACKPROC PauseTransformFeedback;
		extern RNAPI PFNGLRESUMETRANSFORMFEEDBACKPROC ResumeTransformFeedback;
		extern RNAPI PFNGLDRAWTRANSFORMFEEDBACKPROC DrawTransformFeedback;
		extern RNAPI PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC DrawTransformFeedbackStream;
		extern RNAPI PFNGLBEGINQUERYINDEXEDPROC BeginQueryIndexed;
		extern RNAPI PFNGLENDQUERYINDEXEDPROC EndQueryIndexed;
		extern RNAPI PFNGLGETQUERYINDEXEDIVPROC GetQueryIndexediv;

		// 4.1
		extern RNAPI PFNGLRELEASESHADERCOMPILERPROC ReleaseShaderCompiler;
		extern RNAPI PFNGLSHADERBINARYPROC ShaderBinary;
		extern RNAPI PFNGLGETSHADERPRECISIONFORMATPROC GetShaderPrecisionFormat;
		extern RNAPI PFNGLDEPTHRANGEFPROC DepthRangef;
		extern RNAPI PFNGLCLEARDEPTHFPROC ClearDepthf;
		extern RNAPI PFNGLGETPROGRAMBINARYPROC GetProgramBinary;
		extern RNAPI PFNGLPROGRAMBINARYPROC ProgramBinary;
		extern RNAPI PFNGLPROGRAMPARAMETERIPROC ProgramParameteri;
		extern RNAPI PFNGLUSEPROGRAMSTAGESPROC UseProgramStages;
		extern RNAPI PFNGLACTIVESHADERPROGRAMPROC ActiveShaderProgram;
		extern RNAPI PFNGLCREATESHADERPROGRAMVPROC CreateShaderProgramv;
		extern RNAPI PFNGLBINDPROGRAMPIPELINEPROC BindProgramPipeline;
		extern RNAPI PFNGLDELETEPROGRAMPIPELINESPROC DeleteProgramPipelines;
		extern RNAPI PFNGLGENPROGRAMPIPELINESPROC GenProgramPipelines;
		extern RNAPI PFNGLISPROGRAMPIPELINEPROC IsProgramPipeline;
		extern RNAPI PFNGLGETPROGRAMPIPELINEIVPROC GetProgramPipelineiv;
		extern RNAPI PFNGLPROGRAMUNIFORM1IPROC ProgramUniform1i;
		extern RNAPI PFNGLPROGRAMUNIFORM1IVPROC ProgramUniform1iv;
		extern RNAPI PFNGLPROGRAMUNIFORM1FPROC ProgramUniform1f;
		extern RNAPI PFNGLPROGRAMUNIFORM1FVPROC ProgramUniform1fv;
		extern RNAPI PFNGLPROGRAMUNIFORM1DPROC ProgramUniform1d;
		extern RNAPI PFNGLPROGRAMUNIFORM1DVPROC ProgramUniform1dv;
		extern RNAPI PFNGLPROGRAMUNIFORM1UIPROC ProgramUniform1ui;
		extern RNAPI PFNGLPROGRAMUNIFORM1UIVPROC ProgramUniform1uiv;
		extern RNAPI PFNGLPROGRAMUNIFORM2IPROC ProgramUniform2i;
		extern RNAPI PFNGLPROGRAMUNIFORM2IVPROC ProgramUniform2iv;
		extern RNAPI PFNGLPROGRAMUNIFORM2FPROC ProgramUniform2f;
		extern RNAPI PFNGLPROGRAMUNIFORM2FVPROC ProgramUniform2fv;
		extern RNAPI PFNGLPROGRAMUNIFORM2DPROC ProgramUniform2d;
		extern RNAPI PFNGLPROGRAMUNIFORM2DVPROC ProgramUniform2dv;
		extern RNAPI PFNGLPROGRAMUNIFORM2UIPROC ProgramUniform2ui;
		extern RNAPI PFNGLPROGRAMUNIFORM2UIVPROC ProgramUniform2uiv;
		extern RNAPI PFNGLPROGRAMUNIFORM3IPROC ProgramUniform3i;
		extern RNAPI PFNGLPROGRAMUNIFORM3IVPROC ProgramUniform3iv;
		extern RNAPI PFNGLPROGRAMUNIFORM3FPROC ProgramUniform3f;
		extern RNAPI PFNGLPROGRAMUNIFORM3FVPROC ProgramUniform3fv;
		extern RNAPI PFNGLPROGRAMUNIFORM3DPROC ProgramUniform3d;
		extern RNAPI PFNGLPROGRAMUNIFORM3DVPROC ProgramUniform3dv;
		extern RNAPI PFNGLPROGRAMUNIFORM3UIPROC ProgramUniform3ui;
		extern RNAPI PFNGLPROGRAMUNIFORM3UIVPROC ProgramUniform3uiv;
		extern RNAPI PFNGLPROGRAMUNIFORM4IPROC ProgramUniform4i;
		extern RNAPI PFNGLPROGRAMUNIFORM4IVPROC ProgramUniform4iv;
		extern RNAPI PFNGLPROGRAMUNIFORM4FPROC ProgramUniform4f;
		extern RNAPI PFNGLPROGRAMUNIFORM4FVPROC ProgramUniform4fv;
		extern RNAPI PFNGLPROGRAMUNIFORM4DPROC ProgramUniform4d;
		extern RNAPI PFNGLPROGRAMUNIFORM4DVPROC ProgramUniform4dv;
		extern RNAPI PFNGLPROGRAMUNIFORM4UIPROC ProgramUniform4ui;
		extern RNAPI PFNGLPROGRAMUNIFORM4UIVPROC ProgramUniform4uiv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX2FVPROC ProgramUniformMatrix2fv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX3FVPROC ProgramUniformMatrix3fv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX4FVPROC ProgramUniformMatrix4fv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX2DVPROC ProgramUniformMatrix2dv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX3DVPROC ProgramUniformMatrix3dv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX4DVPROC ProgramUniformMatrix4dv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC ProgramUniformMatrix2x3fv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC ProgramUniformMatrix3x2fv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC ProgramUniformMatrix2x4fv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC ProgramUniformMatrix4x2fv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC ProgramUniformMatrix3x4fv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC ProgramUniformMatrix4x3fv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC ProgramUniformMatrix2x3dv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC ProgramUniformMatrix3x2dv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC ProgramUniformMatrix2x4dv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC ProgramUniformMatrix4x2dv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC ProgramUniformMatrix3x4dv;
		extern RNAPI PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC ProgramUniformMatrix4x3dv;
		extern RNAPI PFNGLVALIDATEPROGRAMPIPELINEPROC ValidateProgramPipeline;
		extern RNAPI PFNGLGETPROGRAMPIPELINEINFOLOGPROC GetProgramPipelineInfoLog;
		extern RNAPI PFNGLVERTEXATTRIBL1DPROC VertexAttribL1d;
		extern RNAPI PFNGLVERTEXATTRIBL2DPROC VertexAttribL2d;
		extern RNAPI PFNGLVERTEXATTRIBL3DPROC VertexAttribL3d;
		extern RNAPI PFNGLVERTEXATTRIBL4DPROC VertexAttribL4d;
		extern RNAPI PFNGLVERTEXATTRIBL1DVPROC VertexAttribL1dv;
		extern RNAPI PFNGLVERTEXATTRIBL2DVPROC VertexAttribL2dv;
		extern RNAPI PFNGLVERTEXATTRIBL3DVPROC VertexAttribL3dv;
		extern RNAPI PFNGLVERTEXATTRIBL4DVPROC VertexAttribL4dv;
		extern RNAPI PFNGLVERTEXATTRIBLPOINTERPROC VertexAttribLPointer;
		extern RNAPI PFNGLGETVERTEXATTRIBLDVPROC GetVertexAttribLdv;
		extern RNAPI PFNGLVIEWPORTARRAYVPROC ViewportArrayv;
		extern RNAPI PFNGLVIEWPORTINDEXEDFPROC ViewportIndexedf;
		extern RNAPI PFNGLVIEWPORTINDEXEDFVPROC ViewportIndexedfv;
		extern RNAPI PFNGLSCISSORARRAYVPROC ScissorArrayv;
		extern RNAPI PFNGLSCISSORINDEXEDPROC ScissorIndexed;
		extern RNAPI PFNGLSCISSORINDEXEDVPROC ScissorIndexedv;
		extern RNAPI PFNGLDEPTHRANGEARRAYVPROC DepthRangeArrayv;
		extern RNAPI PFNGLDEPTHRANGEINDEXEDPROC DepthRangeIndexed;
		extern RNAPI PFNGLGETFLOATI_VPROC GetFloati_v;
		extern RNAPI PFNGLGETDOUBLEI_VPROC GetDoublei_v;
	}

#if RN_PLATFORM_WINDOWS
	namespace wgl
	{
		extern RNAPI PFNWGLCREATECONTEXTATTRIBSARBPROC CreateContextAttribsARB;
		extern RNAPI PFNWGLCHOOSEPIXELFORMATARBPROC ChoosePixelFormatARB;
		extern RNAPI PFNWGLSWAPINTERVALEXTPROC SwapIntervalEXT;
		extern RNAPI PFNWGLGETEXTENSIONSSTRINGARBPROC GetExtensionsStringARB;
	}
#endif
}

#endif /* __RAYNE_OPENGL_H__ */
