cd /D "%~dp0"
@RD /S /Q "../Modules/Vulkan/Resources"
@RD /S /Q "../Modules/D3D12/Resources"
python ../Tools/ShaderProcessor/convert.py NoShadows/Shaders.json spirv ../Modules/Vulkan/Resources ":RayneVulkan:"
python ../Tools/ShaderProcessor/convert.py Shadows/Shaders.json spirv ../Modules/D3D12/Resources ":RayneD3D12:"
