
macro(copy_resources _RESOURCES _TARGET)

    foreach(_RESOURCE ${_RESOURCES})
		if(MSVC)
            if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${_RESOURCE}")
            	add_custom_command(TARGET ${_TARGET} PRE_BUILD COMMAND ${CMAKE_COMMAND} -E copy_directory "${CMAKE_CURRENT_SOURCE_DIR}/${_RESOURCE}" "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/$(ConfigurationName)/${_RESOURCE}")
        	else()
           	 	add_custom_command(TARGET ${_TARGET} PRE_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_CURRENT_SOURCE_DIR}/${_RESOURCE}" "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/$(ConfigurationName)/${_RESOURCE}")
        	endif()
        else()
            if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${_RESOURCE}")
            	add_custom_command(TARGET ${_TARGET} PRE_BUILD COMMAND ${CMAKE_COMMAND} -E copy_directory "${CMAKE_CURRENT_SOURCE_DIR}/${_RESOURCE}" "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${_RESOURCE}")
        	else()
            	add_custom_command(TARGET ${_TARGET} PRE_BUILD COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_CURRENT_SOURCE_DIR}/${_RESOURCE}" "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${_RESOURCE}")
        	endif()
        endif()
    endforeach()

endmacro()
